### ISSUE TITLE
Iron man 2

### ISSUE THREAD

**Issue by Rhishilol** [xenia-project/game-compatibility#1004]
[Marketplace](http://marketplace.xbox.com/...)

Tested on (xenia commit link)

# Issues:
(state of the game)

# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here (replacing this text).

# Screenshot(s):
![](Screenshot URL)

# Labels:
(recommended labels)

**Comment by Sleepy93** [comment]
duplicated and incorrect... 

Correct is: #995
