### ISSUE TITLE
w

### ISSUE THREAD

**Issue by Artyr1972200** [xenia-project/game-compatibility#1007]
[Marketplace](http://marketplace.xbox.com/...)

Tested on (xenia commit link)

# Issues:
(state of the game)

# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here (replacing this text).

# Screenshot(s):
![](Screenshot URL)

# Labels:
(recommended labels)

**Comment by tjd2** [comment]
PLEASE DO NOT SPAM!
Is spamming good for you? Is it funny or what?!
Are you spambot?
