### ISSUE TITLE
4D5307D2 - Kameo: Elements of Power

### ISSUE THREAD

**Issue by dude24760** [xenia-project/game-compatibility#1008]
[Marketplace](https://www.microsoft.com/en-gb/p/kameo/bpvp56vrvlz7)

Tested on (https://github.com/xenia-project/xenia/commit/ba7dc6b2d7187a233d7175c75994828b498bec58)

# Issues:
Game loads fine with sound right until the PRESS START screen. Then, unless you had set the CPU time scalar to run at x2 before loading the game, the sound for the first menu does not work, and the game will freeze on the loading screen. Otherwise, the game loads in with some visual bugs, no sound, and completely freezes within the first 5 minutes of gameplay. Saving does not work, shown in the screenshots.

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/2166341/xenia.zip)
[beforecpuscalarx2.zip](https://github.com/xenia-project/game-compatibility/files/2166415/beforecpuscalarx2.zip)
[aftercpu.zip](https://github.com/xenia-project/game-compatibility/files/2166416/aftercpu.zip)

# Screenshot(s):
![soundworking](https://user-images.githubusercontent.com/11066020/42320888-e0a6394a-804e-11e8-9fbc-634b09ae97c5.png)
The sound always works up until after this menu (which I think is a video?)

![save](https://user-images.githubusercontent.com/11066020/42320914-efe8636a-804e-11e8-83c3-870544c03f1a.png)
You cannot load save files created by the game.

![freeze](https://user-images.githubusercontent.com/11066020/42320921-f8b96fe8-804e-11e8-8e5e-58c8706d8275.png)
If you don't have the CPU time scalar running at x2 before the game is opened, the game will completely freeze on the first loading screen.

![afterloading](https://user-images.githubusercontent.com/11066020/42320967-197e8290-804f-11e8-8d52-258dd2dae789.png)
This cutscene (which I believe is also a video like the start screen but could be wrong) also has no sound.

![corrupt1](https://user-images.githubusercontent.com/11066020/42320935-00f40628-804f-11e8-9f9e-e84e033925ae.png)
Visual bug with the blue aura around the character, not there in the actual game.

![corrupt2](https://user-images.githubusercontent.com/11066020/42320950-0c4b23e4-804f-11e8-8019-f2b8bffeea03.png)
The skybox appears to be missing and there is a blue-ish box around all of the "background" dragons (either originally there but blended in with the skybox or another bug)

![crash](https://user-images.githubusercontent.com/11066020/42321057-6e512430-804f-11e8-9182-f6ff22c6c3e9.png)
The game (seemingly) randomly crashes very early on, possibly when some kind of event is triggered which can't be handled (might be in the logs).

#Extra-info:
I've checked the game files, and the intros are indeed .bik video files with audio. A large amount of the game cutscenes/clips, however, have minimal audio, and seemingly rely on some external audio being played, hence why there is no sound after the menu screen. The audio files are also in xwb format.

# Labels:
(state-gameplay apu-silent kernel-save-file-errors gpu-corrupt-drawing gpu-missing-drawing cpu-jit-problems)

**Comment by dude24760** [comment]
Sorry, I didn't notice. But this is the full version, whereas the other thread was just the demo it seems.

**Comment by Parovozik** [comment]
no, there full version, same as here
