### ISSUE TITLE
Got It

### ISSUE THREAD

**Issue by HuseyinStrafer** [xenia-project/game-compatibility#1015]
[Marketplace](http://marketplace.xbox.com/...)

Tested on (xenia commit link)

# Issues:
(state of the game)

# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here (replacing this text).

# Screenshot(s):
![](Screenshot URL)

# Labels:
(recommended labels)

**Comment by Half-asian** [comment]
Nice one

**Comment by tjd2** [comment]
What did you got?
