### ISSUE TITLE
how do i get the file??

### ISSUE THREAD

**Issue by ok122234** [xenia-project/game-compatibility#1016]
how do i get the file??

**Comment by tgsm** [comment]
you dump it?

**Comment by tjd2** [comment]
What file? Xenia, games, log, source code?

**Comment by ok122234** [comment]
the game file (to run it on xenia)

**Comment by tjd2** [comment]
there are few ways to do it:

1. Dump it from your xbox
2. Ebay
3. Other shops, eshops
BTW: label-invalid?

**Comment by ok122234** [comment]
eshops? can you list some of them?

**Comment by tjd2** [comment]
Can someone please close this issue?
