### ISSUE TITLE
464F0803 - Sniper Elite 3

### ISSUE THREAD

**Issue by zemzema** [xenia-project/game-compatibility#1052]
[Marketplace](https://marketplace.xbox.com/en-us/Product/Sniper-Elite-3/66acd000-77fe-1000-9115-d802464f0803)

Tested on https://github.com/benvanik/xenia/commit/ba7dc6b2d7187a233d7175c75994828b498bec58

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/2241371/xenia.zip)

# Screenshot(s):
![screenshot 119](https://user-images.githubusercontent.com/33085810/43401535-af36f752-9410-11e8-9497-fd1075e4f545.png)
![screenshot 120](https://user-images.githubusercontent.com/33085810/43401536-af54fe82-9410-11e8-8f86-91dc0fe5b3d0.png)

# Labels:
 (state-load)(state-host-crash)

**Comment by illusion98** [comment]
Ingame https://github.com/xenia-project/xenia/commit/f7ea93148a9ec9ff0ad9edac8c01854bd6153a10
![a](https://cdn.discordapp.com/attachments/561407879823753217/592382321307418638/unknown.png)

**Comment by Margen67** [comment]
Duplicate of #688

**Comment by Ulquiorr4-Cifer** [comment]
> Duplicate of #688

closed
