### ISSUE TITLE
5841092A - Mega Man 9

### ISSUE THREAD

**Issue by EIREXE** [xenia-project/game-compatibility#107]
[Marketplace](http://marketplace.xbox.com/en-US/Product/MEGA-MAN-9/66acd000-77fe-1000-9115-d8025841092a)

Tested against https://github.com/xenia-project/xenia/commit/226b7ae83f52fd5f2e923377ca374ea3b7223ba0

# Issues
There seems to be a projection issue in the game, under the hood it seems to be running flawlessly.

# Screenshots
![xenia_2015-07-29_06-25-06](https://cloud.githubusercontent.com/assets/3101690/8949937/b3377d84-35ba-11e5-9e6f-8c004451b54d.png)

# Labels
state-playable gpu-corrupt-drawing

**Comment by EIREXE** [comment]
State-playable gpu-corrupt-drawing

By the way, how can I get logs for the games?

**Comment by raven02** [comment]
It looks like it is rect list issue https://github.com/benvanik/xenia/issues/304

**Comment by Razzile** [comment]
I'd also like to point out geometry wars 2 and marble blast ultra have similar projection issues. I will file separate reports for them later

**Comment by HorrorTroll** [comment]
![image](https://cloud.githubusercontent.com/assets/24840279/21577863/579c4f12-cf9d-11e6-8e9d-8b33c37d5b36.png)

It's fix but with some buggy like the screen is stretch, invert color

**Comment by bdeimos** [comment]
#727 is more relevant.
