### ISSUE TITLE
555307DC - Far Cry: Instincts Predator

### ISSUE THREAD

**Issue by grandshot** [xenia-project/game-compatibility#1083]
[Marketplace](http://marketplace.xbox.com/en-us/Product/FC-Instincts-Predator/66acd000-77fe-1000-9115-d802555307dc)

Tested on (https://github.com/xenia-project/xenia/commit/c624bf8c496ec1c13d79b6cc9368d2dd2c94652d)

# Issues:
Using a 'little trick', I launched a second level - 01_Beach instead first.
There's more 'action' in gameplay, so it's a good stress test for emulation state.

Well, playable state so quite to very well. Level can be completed without any problems. Emulator doesn't crash even after many restarts, checkpoints work. On my hardware stable 30 fps at the any stages.

There are graphic and sounds issues, but now is little more interesting.

If get a boat, water shader become to visible. Restart checkpoint and ocean view will be better yet.

Sound work at the start, but  dissapear when player entering in any building (In engine: Sound area changes from outdoor to indoor, sounds off and don't restore). Restart doesn't help.

In other shaders bugs:
-Very intensive bloom (Terrain heat effect?). Screen space just fill of white. Sometimes disappear, after load checkpoints predominantly, but returns later. 

 -Flickering grass (Is alphablending issue?).

And in conclusion - glutches with dynamic shadows.

Gameplay is here: [[Xenia c624bf8c] Far Cry Instincts: Predator - Level 01 Beach](https://youtu.be/SwvfHrfeTSI)
Sound issue at the [10:06](https://youtu.be/SwvfHrfeTSI?t=606)
# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/2448178/xenia.zip).

# Screenshot(s):
![desktop screenshot 2018 10 04 - 23 23 07 19](https://user-images.githubusercontent.com/43651969/46506058-bc258000-c83b-11e8-90bb-d06fcc27301d.png)
![desktop screenshot 2018 10 04 - 23 26 27 28](https://user-images.githubusercontent.com/43651969/46506062-c21b6100-c83b-11e8-8592-2b2eb84fca48.png)
![desktop screenshot 2018 10 04 - 23 26 42 75](https://user-images.githubusercontent.com/43651969/46506067-c3e52480-c83b-11e8-96ed-9e7c7e6a145f.png)
![desktop screenshot 2018 10 04 - 23 23 44 17](https://user-images.githubusercontent.com/43651969/46506145-0444a280-c83c-11e8-87cb-7d1a3d3b1613.png)
![desktop screenshot 2018 10 04 - 23 27 47 52](https://user-images.githubusercontent.com/43651969/46506073-c8a9d880-c83b-11e8-8fe9-d8f14fd19b37.png)
![desktop screenshot 2018 10 04 - 23 59 20 47](https://user-images.githubusercontent.com/43651969/46506074-ca739c00-c83b-11e8-91cf-7b485ff2a67a.png)
![desktop screenshot 2018 10 04 - 23 57 46 90](https://user-images.githubusercontent.com/43651969/46506075-cba4c900-c83b-11e8-98e9-ef85d4ddc3f8.png)

# Labels:
gpu-shader-errors
state-gameplay

**Comment by gibbed** [comment]
#979
