### ISSUE TITLE
Halo 3 Black Screen 

### ISSUE THREAD

**Issue by ProblemO** [xenia-project/game-compatibility#1084]
[Marketplace](http://marketplace.xbox.com/en-us/Product/Halo-3/66acd000-77fe-1000-9115-d8024d5307e6)

<!--

Tested on (didn't understand this quiet well sorry .. but i tried it in the last version of xenia)

# Issues:
(black screen)

)

# Log:
([xenia.zip](https://github.com/xenia-project/game-compatibility/files/2450877/xenia.zip).

# Screenshot(s):
![](Screenshot URL)

# Labels:
(apu-garbage)

**Comment by ProblemO** [comment]
why closed ?

**Comment by Ulquiorr4-Cifer** [comment]
> why closed ?

check other reports and see how yours is different

**Comment by ProblemO** [comment]
> > why closed ?
> 
> check other reports and see how yours is different

other reported like mine are from 2015 ...!!
