### ISSUE TITLE
call of duty

### ISSUE THREAD

**Issue by ulisesmarce23** [xenia-project/game-compatibility#1091]
[Marketplace](http://marketplace.xbox.com/...)

Tested on (xenia commit link)

# Issues:
(state of the game)

# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here (replacing this text).

# Screenshot(s):
![](Screenshot URL)

# Labels:
(recommended labels)

**Comment by PersonalityPi** [comment]
Think you could actually fill the post it BEFORE posting it?
