### ISSUE TITLE
DRG ZDRG

### ISSUE THREAD

**Issue by edgar1254** [xenia-project/game-compatibility#1094]
[Marketplace](http://marketplace.xbox.com/...)

Tested on (xenia commit link)

# Issues:
(state of the game)

# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here (replacing this text).

# Screenshot(s):
![](Screenshot URL)

# Labels:
(recommended labels)

**Comment by PersonalityPi** [comment]
think you could actually fill the post it BEFORE posting it?

**Comment by some-username-here1** [comment]
And also Game Title ID, too
