### ISSUE TITLE
4D5307E6 - Halo 3

### ISSUE THREAD

**Issue by ReclaimerShawn** [xenia-project/game-compatibility#1122]
[Marketplace] https://marketplace.xbox.com/en-us/Product/Halo-3/66acd000-77fe-1000-9115-d8024d5307e6

Tested on: xenia-project/xenia@76989446

# Issues:
Using a modded .xex, Halo 3 crashes right after the Bungie logo disappears. I also had a lot of extra maps added to the maps folder, so I don't know if I overloaded Xenia or not. I've included the modded .xex, as well as the Xenia log file. This XEX is the Halo 3 XEX with this patch applied:
https://www.xboxchaos.com/topic/3273-halo-3-ultimate-xex-ppf-patches/

# Log:
[Xenia.zip](https://github.com/xenia-project/game-compatibility/files/2664656/Xenia.zip)

# Default XEX:
[Modded Halo 3 Default.zip](https://github.com/xenia-project/game-compatibility/files/2664657/Modded.Halo.3.Default.zip)

# Screenshot(s):
![issue1](https://user-images.githubusercontent.com/30769105/49757057-7a74e380-fc89-11e8-984e-a24e18faf38e.png)
![issue2](https://user-images.githubusercontent.com/30769105/49757080-86f93c00-fc89-11e8-96a9-0c5cb2989347.png)
![issue3](https://user-images.githubusercontent.com/30769105/49757098-8fea0d80-fc89-11e8-90f7-ade85f71fd4b.png)

# Labels:
state-crash-guest

**Comment by gibbed** [comment]
#178 

That being said, until Xenia in a stable place, you should not be reporting issues with modified content.
