### ISSUE TITLE
Sonic the hedgehog is playable on Xenia now

### ISSUE THREAD

**Issue by nyonthecat** [xenia-project/game-compatibility#1131]
Tested on Xenia Vulkan 30-12-2018
Fully playable!
![20181230160942_1 - copia](https://user-images.githubusercontent.com/44591521/50551043-e976a400-0c59-11e9-8157-11fd12c64d7b.jpg)

**Comment by Exayne** [comment]
I used vulkan and it didn't work however it's playable on d3d12
