### ISSUE TITLE
58410872 - E4: Every Extend Extra Extreme

### ISSUE THREAD

**Issue by mrlionx** [xenia-project/game-compatibility#1141]
[Marketplace](https://www.microsoft.com/en-us/p/e4/bs7bxgc854nk?activetab=pivot:overviewtab.)

Tested on (https://github.com/xenia-project/xenia/commit/61fd5a6dc24543f39c3a17976d762e7d67abba33)

# Issues:
Stuck on initial loading screen.  Goes through the dev logos and then gets stuck on now loading after.

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/2801498/xenia.zip)

# Screenshot(s):
![](https://i.imgur.com/1Hky6TP.png)

# Labels:
state-intro

**Comment by zefie** [comment]
dupe of #809, if it helps.
Also note that the graphics are still majorly incorrect in the Vulkan build, but renders correctly in d3d12 build. Both hang at the same spot.

**Comment by win98and95** [comment]
@zefie
Tell @Razzile on [discord](https://discord.gg/5g93S8H)
