### ISSUE TITLE
MetalGearRising demo

### ISSUE THREAD

**Issue by strangermoon** [xenia-project/game-compatibility#1152]
[Marketplace](http://marketplace.xbox.com/...)

Tested on (Xenia commit link)

# Issues:
(state of the game)

# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here (replacing this text).

# Screenshot(s):
![](Screenshot URL)

# Labels:
(recommended labels)

**Comment by strangermoon** [comment]
played demo works fine.

**Comment by ZolaKluke** [comment]
You didn't follow the template

**Comment by ZolaKluke** [comment]
This is a good example of how it should be done: https://github.com/xenia-project/game-compatibility/issues/1150
