### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by amiNO4** [xenia-project/game-compatibility#1157]
[Marketplace](http://marketplace.xbox.com/...)

Tested on (Xenia commit link)

# Issues:
(state of the game)

# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here (replacing this text).

# Screenshot(s):
![](Screenshot URL)

# Labels:
(recommended labels)

**Comment by ZolaKluke** [comment]
Can you close this issue
