### ISSUE TITLE
Halo 3 Beta (Done right)

### ISSUE THREAD

**Issue by sethandthecrew** [xenia-project/game-compatibility#1159]
{4D53880C} - {HALO 3 BETA BULID FROM MAY-JUNE 2007}

If you have trouble finding it, Try Google: "Halo 3 Beta Download"

Tested on Xenia March 7th 2019

# Issues:
(Disk read error ‘crash’ upon startup of Halo3_tu2.xex file)

# Log:

# Screenshot(s):

# Labels:

**Comment by Margen67** [comment]
>Done right

Not really.
