### ISSUE TITLE
415607DD - Tony Hawk's Project 8

### ISSUE THREAD

**Issue by Momoske** [xenia-project/game-compatibility#1161]
Tony Hawk's Project 8

Tested on both https://github.com/xenia-project/xenia/commit/d3d12 AND https://github.com/xenia-project/xenia/commit/master

# Issues:
Game won't boot past the loading screen (which only appears on Xenia D3D12, nothing at all on vulkan)

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/3050853/xenia.zip)

# Screenshot(s):
https://gyazo.com/ce7dfbe0e7a270629136df5f4993ac68

# Labels:
state-hang / marketplace-unlisted

**Comment by EpicFoxx64** [comment]
Repeat of https://github.com/xenia-project/game-compatibility/issues/956
