### ISSUE TITLE
584114B0 - Prison Architect

### ISSUE THREAD

**Issue by dsk80004** [xenia-project/game-compatibility#1168]
[Marketplace](https://marketplace.xbox.com/en-US/Product/Prison-Architect-Xbox-360-Edition/66acd000-77fe-1000-9115-d802584114b0)

Tested on (Xenia April 9 2019 Vulkan)

# Issues:
Frame skips, and lag. With no input functions working after boot.

(Sorry I know this isn't proper but was really only planning on updating posts, not creating a new one)

**Comment by Ulquiorr4-Cifer** [comment]
edit this to match other compatibility reports
