### ISSUE TITLE
44500805 - Earth Defense 2025

### ISSUE THREAD

**Issue by sharkboy1006** [xenia-project/game-compatibility#1175]
Marketplace: https://marketplace.xbox.com/en-us/Product/Earth-Defense-Force-2025/66acd000-77fe-1000-9115-d80244500805
Tested on https://ci.appveyor.com/project/benvanik/xenia/builds/24133061

# Issues:
Menus work, freeze upon loading into game

# Log:
https://github.com/xenia-project/game-compatibility/files/3123264/xenia.zip

# Screenshot(s):
![image](https://user-images.githubusercontent.com/39467208/56841450-d9637f80-685b-11e9-8e5e-dcf7f4d96f27.png)
Character appears to render properly ![image](https://user-images.githubusercontent.com/39467208/56841459-e5e7d800-685b-11e9-8129-82c2cd811c44.png)

# Video: https://youtu.be/i6RFWWmUqw0

# Labels:
state-menus

**Comment by illusion98** [comment]
Pirated release. Please dump the game using our [guide](https://github.com/xenia-project/xenia/wiki/How-to-rip-games). Closing.
