### ISSUE TITLE
Sonic The Hedgehog freezing

### ISSUE THREAD

**Issue by silver231** [xenia-project/game-compatibility#1219]
STH 2006 on vulcan freezes for me often and prevents me from progressing in the game. I can usually run it at an okay framerate on the latest bulid of xenia. Trigger points are usually when a cutscene's about to play, but it's not consistent and sometimes works, other times it doesn't. I am currently stuck at the point after the Egg Cerberus fight, where the stage complete music plays, but i am left on the frozen loading screen, xenia hangs up and crashes afterwards. I tried beating it about 5 times and it still doesn't want to load. I am using the vulcan cache fix. I have both the vulcan sdk and runtime. The custom build for 06 won't start due to vulcan related issues, if someone were to suggest that. My specs might have something to do with this, but i doubt it, since the game runs at something near 30-45 fps territory usually. Here they are:
AMD Ryzen 5 2500-U mobile
Vega 8 integrated graphics card
8GB of RAM
Does anybody know what is the issue and how to fix it?

**Comment by silver231** [comment]
Oh yeah I forgot: My radeon software version is 19.5.1

**Comment by win98and95** [comment]
DO NOT CREATE ISSUES ABOUT SPECIFIC GAMES IN THIS REPOSITORY!
THIS IS NOT A SUPPORT FORUM! For support go here:
Xenia Discord (#help) - https://discord.me/xenia-emulator

**Comment by Margen67** [comment]
Duplicate of #285
