### ISSUE TITLE
margen67

### ISSUE THREAD

**Issue by walkerdead1** [xenia-project/game-compatibility#1289]
[Marketplace](http://marketplace.xbox.com/...)

Tested on (Xenia commit link)

# Issues:
(state of the game)

# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here (replacing this text).

# Screenshot(s):
![](Screenshot URL)

# Labels:
(recommended labels)

**Comment by Margen67** [comment]
walkerdead1

**Comment by illusion98** [comment]
Margen76
