### ISSUE TITLE
58410A9F -The Fancy Pants Adventures

### ISSUE THREAD

**Issue by N00BKillY** [xenia-project/game-compatibility#1319]
[Marketplace]https://marketplace.xbox.com/en-US/Product/The-Fancy-Pants-Adventures/66acd000-77fe-1000-9115-d80258410a9f

Tested on (Xenia commit link)

# Issues:
(state of the game)

# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here (replacing this text).

# Screenshot(s):
![](Screenshot URL)

# Labels:
(recommended labels)

**Comment by Ulquiorr4-Cifer** [comment]
Pls edit to follow template, closed for now

**Comment by illusion98** [comment]
duplicate of https://github.com/xenia-project/game-compatibility/issues/40
