### ISSUE TITLE
{GAME TITLE ID} - {GAME NAME}

### ISSUE THREAD

**Issue by thearturord** [xenia-project/game-compatibility#1383]
[Marketplace](http://marketplace.xbox.com/...)
https://www.microsoft.com/en-us/p/fable-ii/c2wkjj9f5936

Tested on (Xenia commit link)

# Issues:
(state of the game)

# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here (replacing this text).

# Screenshot(s):
![](Screenshot URL)

# Labels:
(recommended labels)

**Comment by Margen67** [comment]
An issue already exists for Fable II: #205
