### ISSUE TITLE
4D530AB5 - Forza Horizon 2 Fast&Furious Edition

### ISSUE THREAD

**Issue by HyproZe** [xenia-project/game-compatibility#1402]
[Marketplace](https://marketplace.xbox.com/en-US/Product/Forza-Horizon-2-Presents-Fast-Furious/66acd000-77fe-1000-9115-d8024d530ab5)

Tested on xenia-project/xenia@ed7ac161

# Issues:
In-game but somes textures are broken
Intro and cutscenes runs perfectly
Some collisions is broken (betweens cars and somes barriers)

# Log:
Too big 2Go for 9mins

# Screenshot(s):
![image](https://user-images.githubusercontent.com/49229052/64284453-ed319780-cf59-11e9-9591-5c0ecc93a3c0.png)
![image](https://user-images.githubusercontent.com/49229052/64284489-00dcfe00-cf5a-11e9-8a14-534f7465b396.png)
![image](https://user-images.githubusercontent.com/49229052/64284511-0cc8c000-cf5a-11e9-9fdb-e9a66732629b.png)
![image](https://user-images.githubusercontent.com/49229052/64284517-12260a80-cf5a-11e9-9d28-900b81db6bb6.png)
![image](https://user-images.githubusercontent.com/49229052/64284528-181beb80-cf5a-11e9-87f7-c8f3a59b9823.png)
![image](https://user-images.githubusercontent.com/49229052/64284581-371a7d80-cf5a-11e9-9065-4bc8be7eac82.png)
![image](https://user-images.githubusercontent.com/49229052/64284595-3d105e80-cf5a-11e9-92b5-23c93d02e436.png)
![image](https://user-images.githubusercontent.com/49229052/64284610-46013000-cf5a-11e9-9828-4e648fa22919.png)
![image](https://user-images.githubusercontent.com/49229052/64284620-4a2d4d80-cf5a-11e9-87bb-adfa42b535a1.png)
![image](https://user-images.githubusercontent.com/49229052/64284637-587b6980-cf5a-11e9-96aa-4101145cf77d.png)

# Labels:
state-gameplay

**Comment by HOS2002** [comment]
How did you get the ISO/files for the game if you don't mind me asking?

**Comment by serho121** [comment]
how to download file for forza horizon 2 ?

**Comment by Margen67** [comment]
@serho121 https://github.com/xenia-project/xenia/wiki/Quickstart#how-to-rip-games

**Comment by Margen67** [comment]
#1762
