### ISSUE TITLE
[54540859] - Top Spin 4 - Game crash before main menu

### ISSUE THREAD

**Issue by sous0u** [xenia-project/game-compatibility#1430]
[Marketplace](http://marketplace.xbox.com/...)

Tested on (Xenia commit link)

# Issues:
Weird things happened - I was able to play 1 full game, then when I relaunched it impossible to reach the main menu. I tried 100 times I surrender

Please help :)

Thanks
# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here (replacing this text).

# Screenshot(s):
![](Screenshot URL)

# Labels:
(recommended labels)

**Comment by Triang3l** [comment]
Duplicate of #867 with improper formatting.
