### ISSUE TITLE
58410865 - Prince of Persia Classic (XBLA)

### ISSUE THREAD

**Issue by Thunderstorm2** [xenia-project/game-compatibility#1434]
Hello Xenia Community, I would like to report about Prince of Persia Classic (Xbox Live Arcade) that menus only are working. I can't post images of it because I'm using another PC.

**Comment by illusion98** [comment]
Not following the provided [template](https://github.com/xenia-project/game-compatibility#submitting-issues). Closed.

**Comment by Margen67** [comment]
#1714
