### ISSUE TITLE
Ace Combat 6: Fires of Liberation. No Sound In Cutscenes.

### ISSUE THREAD

**Issue by RUSE35** [xenia-project/game-compatibility#1444]
Tested on https://github.com/xenia-project/xenia/commit/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# Issues:
Game will reach gameplay but sound in menus constantly loops and cutscenes in-engine have no sound.

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/3664267/xenia.zip)

# Screenshot(s):
It's sound related. Other issues pertaining to gameplay have already been documented.

# Labels:
(recommended labels)
apu-silent
apu-garbage

**Comment by Margen67** [comment]
Inferior duplicate of #419.

**Comment by Margen67** [comment]
Duplicate of #419.
