### ISSUE TITLE
[5451085D] Smackdown VS Raw 2011 

### ISSUE THREAD

**Issue by Goremone** [xenia-project/game-compatibility#1449]
Hey guys!

I wonder, if there's any workaround to save the game,...
![image](https://user-images.githubusercontent.com/56077787/66046792-2b0ce600-e52f-11e9-891b-80354dcb1cc7.png)
 because it still has no option to create player profile or save in any shape or form.

**Comment by Margen67** [comment]
no

**Comment by Margen67** [comment]
#1505
