### ISSUE TITLE
4E4D07E0 - Soulcalibur VI

### ISSUE THREAD

**Issue by WhiteRedWolf** [xenia-project/game-compatibility#1450]
Tested on https://github.com/xenia-project/xenia/commit/f748e5af49062fd78d098acdaf045183f29faf36

# Issues:
The Xenia Emulator Crashes on Bootup

# Log:
[xenia.log](https://github.com/xenia-project/game-compatibility/files/3693613/xenia.log)

# Screenshot(s):

# Labels:
state-crash-host,
state-crash-guest

**Comment by Margen67** [comment]
Missing marketplace link.
Also, there should only be on state label.

**Comment by MarioSonic2987** [comment]
Duplicate of #1128. And there's a typo in the game title. It's SoulCalibur IV.
