### ISSUE TITLE
diablo 3 guest has crashed

### ISSUE THREAD

**Issue by donrogoo** [xenia-project/game-compatibility#1461]
hi i tried to play diablo3 and diablo3 reaper of souls on xenia but they always crash i have windows7 i5-6600processor  8gb ram
gigabyte vidia geforce gt 1030  can you find a solution please ?
![diabloo](https://user-images.githubusercontent.com/57328996/68091524-91b45500-fe89-11e9-860d-bc674d210691.JPG)

**Comment by Margen67** [comment]
Stop spamming.

**Comment by illusion98** [comment]
Pirated copy of the game too.

**Comment by Margen67** [comment]
Duplicate of either #105 or #1114
