### ISSUE TITLE
CPU over GPU ?

### ISSUE THREAD

**Issue by ParkMeteor** [xenia-project/game-compatibility#1463]
Hi everyone,
I discovered Xenia a long time ago and it seems simple to use. But a problem persists. When I run the .ISO image of a game, everything starts as expected but my GPU runs at 20% while my CPU goes up to 100%.

I have an Intel 8700k and a Geforce 1070Ti and I can not find any solution elsewhere.

thank you

**Comment by illusion98** [comment]
GitHub is not for tech support go to our discord server for that

**Comment by Triang3l** [comment]
CPU over GPU — the GPU draws faster than the CPU submits.
GPU over CPU — the CPU submits faster than the GPU draws.
What's wrong with either?
