### ISSUE TITLE
Devil may cry dmc demo

### ISSUE THREAD

**Issue by strangermoon** [xenia-project/game-compatibility#1465]
Playable on XENIA-CUSTOM build 1.11i . some gliches on boss battle.

**Comment by ZolaKluke** [comment]
> Playable on XENIA-CUSTOM build 1.11i . some gliches on boss battle.

Doesn’t follow the format for game compatibility issues and also that is an unofficial build

**Comment by Margen67** [comment]
This isn't the first time, either. @strangermoon Learn how to read: https://github.com/xenia-project/game-compatibility#submitting-issues
