### ISSUE TITLE
Fuzion Frenzy 2

### ISSUE THREAD

**Issue by taiwan-king** [xenia-project/game-compatibility#1471]
![1576350802418](https://user-images.githubusercontent.com/24381898/70853423-e0252c80-1ee8-11ea-95cf-cc5ab1d467f5.jpg)
[xenia.log](https://github.com/xenia-project/game-compatibility/files/3964246/xenia.log)

**Comment by EpicFoxx64** [comment]
Can you please change this so it **actually follows the compatibily template**.

**Comment by Margen67** [comment]
#1530
