### ISSUE TITLE
Peggle 2

### ISSUE THREAD

**Issue by ahmed3110c** [xenia-project/game-compatibility#1473]
The game doesn't load.
Once i open the game, the emulator crashes
![Desktop Screenshot 2019 12 18 - 18 32 37 62](https://user-images.githubusercontent.com/35050653/71104739-f242eb80-21c4-11ea-93f7-fda7029ce07e.png)
[xenia.log](https://github.com/xenia-project/game-compatibility/files/3979445/xenia.log)

**Comment by Margen67** [comment]
Invalid duplicate of #734.
