### ISSUE TITLE
584108C2 The Maw

### ISSUE THREAD

**Issue by wheelmac92** [xenia-project/game-compatibility#1480]
![image](https://user-images.githubusercontent.com/58401060/71494974-3d8a7900-2819-11ea-8030-685cc43d4cf8.png)

Sometimes freezes in the menu, sometimes goes in game. No graphical bugs or sound glitches that I know of, just occasional freezes

**Comment by ZolaKluke** [comment]
Mate none of the issues you’ve made so far follow the template
