### ISSUE TITLE
41560877 - HowToTrainYourDragon

### ISSUE THREAD

**Issue by niko1point0** [xenia-project/game-compatibility#1483]
Xenia Dec 4 2019

Many times, flashing and flickering happens. However, any time you see this glitch, it can be fixed immediately by pressing F4 to flush cache

Before pressing F4:
![image](https://user-images.githubusercontent.com/7824443/71605348-2a87e980-2b36-11ea-98f7-5a9c37e6ed8d.png)

After pressing F4:
![image](https://user-images.githubusercontent.com/7824443/71605359-3a9fc900-2b36-11ea-963a-d58c711e80f1.png)

Before pressing F4:
![image](https://user-images.githubusercontent.com/7824443/71605376-6622b380-2b36-11ea-8601-232ba6bcd489.png)

After pressing F4:
![image](https://user-images.githubusercontent.com/7824443/71605399-979b7f00-2b36-11ea-82c5-1166f84daf36.png)

**Comment by illusion98** [comment]
Not following the issue template.

**Comment by niko1point0** [comment]
I'll submit another issue that follows the template more closely

**Comment by Margen67** [comment]
#1884
