### ISSUE TITLE
4E4D0846 - Dragon Ball Z Ultimate Tenkaichi (HELP)

### ISSUE THREAD

**Issue by TheDominicano** [xenia-project/game-compatibility#1486]
I have booted the game and all and at first it works for me at a good speed! But when I go to the game's menu it sharply slow down and I am not able to play! It is my first time playing on Xenia and I would appreciate some help... I will try another game which is installing at the moment but please help. I have an Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz, 3601 Mhz, 4 Core(s), 8 Logical Processor(s)
I am not a pro in this I just want to play my games ...

**Comment by Margen67** [comment]
Invalid duplicate of #724.
