### ISSUE TITLE
Gears of War 3 crashed with Graphics Device Lost due to an internal error... 

### ISSUE THREAD

**Issue by Pantsay126** [xenia-project/game-compatibility#1488]
Every time I launch Gears of War 3 with Canary Xenia build version 0.0.05699 (January 16, 2020), the game frequently crashed in like 2-5 minutes. How do you fix this crash error? 
![gears 3 crash xenia](https://user-images.githubusercontent.com/49543895/72571658-0ab22e80-3875-11ea-8871-30ae0ae1d29e.PNG)

Spec:
i9-9900k
Windows 10 64-bit Pro
64GB RAM
RTX 2080 Ti
GeForce Driver: 441.87

**Comment by Margen67** [comment]
Tech support belongs in the #help channel on the [Discord server](https://discord.gg/5g93S8H), not here.

**Comment by Margen67** [comment]
Duplicate of #30
