### ISSUE TITLE
545408B2- WWE2K14

### ISSUE THREAD

**Issue by Stephens133** [xenia-project/game-compatibility#1494]
545408B2- WWE2K14
Please help me to fix this issue in WWE2K14
This game is running good at start but when I am starting match the Xenia gets crash by giving this error
Check at 4:45
https://youtu.be/8qFyrsi1ZPc

**Comment by ZolaKluke** [comment]
@Stephens133 
1. That is Xenia-Canary, this branch is the Master builds
2. Github is not for tech support

**Comment by Margen67** [comment]
Learn how to read: https://github.com/xenia-project/game-compatibility#what-not-to-post

**Comment by Margen67** [comment]
Duplicate of #1361
