### ISSUE TITLE
NASCAR The Game: Inside Line

### ISSUE THREAD

**Issue by Scratchalang** [xenia-project/game-compatibility#1497]
415608D2 - NASCAR The Game: Inside Line

[Marketplace](http://marketplace.xbox.com/en-US/Product/NASCAR-Inside-Line/66acd000-77fe-1000-9115-d802415608d2)

Tested on https://github.com/xenia-project/xenia/commit/710d225d0af77f83869e892d2d7377e81bd18bee

# Issues:
The game advances through loading screens. 3D graphics in the menu are not rendered. At the autosave notice screen, the game gets an unavailable storage device error. It is impossible to get past this screen.

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/4271162/xenia.zip)

# Screenshot(s):
![](![Screenshot (35)](https://user-images.githubusercontent.com/60577687/75617036-8e1a9d00-5b0e-11ea-9436-925ac0be24ca.png)

# Labels:
state-title

**Comment by Margen67** [comment]
Superseded by #1498.
