### ISSUE TITLE
415608A4 - Transformers Dark of The Moon

### ISSUE THREAD

**Issue by AleDaz** [xenia-project/game-compatibility#1529]
[Marketplace](http://marketplace.xbox.com/...)

Tested on https://github.com/xenia-project/xenia/commit/660559bd372e34f62979b43fc9bf23b81f236037

# Issues:
Minor lag spikes in very populated areas. Game crashes around every 30 - 40 minutes. The game runs pretty smoothly everywhere else, staying at a near locked 30 fps. The game can be finished. 

# Log:

[xenia.zip](https://github.com/xenia-project/game-compatibility/files/4492882/xenia.zip)

# Screenshot(s):
![Capture](https://user-images.githubusercontent.com/63855107/79569712-21d80680-8086-11ea-8a01-e564a6865889.PNG)

# Labels:
(recommended labels)
 
state-gameplay
tech-physics-physx

**Comment by Swodahs** [comment]
Mine freezes right after the logos as soon as it gets to the menu. Is there a certain build I need to download or right settings I have to input?

**Comment by Margen67** [comment]
Canary reports belong here: https://github.com/xenia-canary/game-compatibility/issues

**Comment by AleDaz** [comment]
> Canary reports belong here: https://github.com/xenia-canary/game-compatibility/issues

MB I'm new to this

**Comment by AleDaz** [comment]
> Canary reports belong here: https://github.com/xenia-canary/game-compatibility/issues



> Canary reports belong here: https://github.com/xenia-canary/game-compatibility/issues



> Mine freezes right after the logos as soon as it gets to the menu. Is there a certain build I need to download or right settings I have to input?

MB Swodahs. I'm using Xenia canary version 660559bd

**Comment by AleDaz** [comment]
MB Swodahs. I'm using Xenia canary version 660559bd

**Comment by Swodahs** [comment]
AleDaz where do you download it? Sorry, I'm new to this

**Comment by Margen67** [comment]
@Swodahs https://github.com/xenia-project/game-compatibility#what-not-to-post
