### ISSUE TITLE
44500801 - Madagascar 3 The Video Game

### ISSUE THREAD

**Issue by Bluely-NO-STALKING-MYSELF-ALLOWED** [xenia-project/game-compatibility#1532]
[Marketplace](https://marketplace.xbox.com/en-GB/Product/Madagascar-3-The-Video-Game/66acd000-77fe-1000-9115-d80244500801)

Tested on: https://github.com/xenia-project/xenia/commit/cf0251cd9f57669320a0ddf774d7b92fd800d0bb

# Issues:
None - Renders Perfectly

# Screenshot(s):
![210](https://user-images.githubusercontent.com/59511669/80092520-4f66f900-8539-11ea-8679-683b36aba924.PNG)
 -->

# Labels:
 #state-gameplay

**Comment by Margen67** [comment]
@BluelyTASer Missing log and marketplace link.

**Comment by BluelyTASer** [comment]
https://marketplace.xbox.com/pt-BR/Product/Madagascar-3-The-Video-Game/66acd000-77fe-1000-9115-d80244500801 and the log i don't have. :hot_face:

**Comment by BluelyTASer** [comment]
Here's my Zip containing log! 😄 
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/4522424/xenia.zip)
