### ISSUE TITLE
4D5309B6 - Kinect Rush: A Disney-Pixar Adventure

### ISSUE THREAD

**Issue by Bluely-NO-STALKING-MYSELF-ALLOWED** [xenia-project/game-compatibility#1538]
Missing marketplace except for snapshot version.
Tested on https://github.com/xenia-project/xenia/commit/f7ad6310574c34c6aed6586d52e6422739c702eb

# Issues:
Freezes when pressing random xbox buttons due to never-going-to-be-implemented kinect support.

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/4549193/xenia.zip)

# Screenshot(s):
![326](https://user-images.githubusercontent.com/59511669/80549827-a2efa180-8994-11ea-9ca1-6e49fdcef6bd.PNG)

# Labels:
tech-kinect-required
marketplace-delisted
state-title

**Comment by kinetic3d** [comment]
never support kinect? :'(
