### ISSUE TITLE
4D5307D2 - Kameo: Elements of Power

### ISSUE THREAD

**Issue by snailmann32** [xenia-project/game-compatibility#1566]
[Marketplace](https://marketplace.xbox.com/en-us/Product/Kameo/66acd000-77fe-1000-9115-d8024d5307d2?downloadType=GameVideo&noSplash=1)

Tested on https://github.com/xenia-project/xenia/commit/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# Issues:
Title screen plays fine, but the main menu's bottom half is missing. Background is pushed into corner. Created save file is not recognized. Game hangs (and crashed once) when proceeding past the menu (having opted to go on without a save). Menu music and sound effects are missing.

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/4672137/xenia.zip)

# Screenshot(s):
![xen2](https://user-images.githubusercontent.com/65823603/82735974-051d9700-9cf4-11ea-9c13-b8818f8c12b9.png)
![xen1](https://user-images.githubusercontent.com/65823603/82735975-077ff100-9cf4-11ea-9e11-4afba3097a21.png)
![xen3](https://user-images.githubusercontent.com/65823603/82735978-0bac0e80-9cf4-11ea-8ce5-abf4f43775de.png)
![xen4](https://user-images.githubusercontent.com/65823603/82735980-0ea6ff00-9cf4-11ea-91d8-bf91634fbbfb.png)
![xen5](https://user-images.githubusercontent.com/65823603/82736074-cb995b80-9cf4-11ea-99eb-2c7fb3ad7eca.png)

# Labels:
kernel-save-file-errors 
state-crash-guest 
gpu-drawing-corrupt
gpu-drawing-missing
gpu-shader-errors

**Comment by snailmann32** [comment]
No explanation?

**Comment by Margen67** [comment]
The commit hash was invalid. Not that it matters since this is a duplicate anyway: #173
