### ISSUE TITLE
545407e5 - CIVILIZATION REVOLUTION

### ISSUE THREAD

**Issue by Mezahhh** [xenia-project/game-compatibility#1571]
Xbox 360 Marketplace links only.
https://www.microsoft.com/fr-fr/p/civilization-revolution/9wzdncrfhxht?activetab=pivot:overviewtab

#Tested: 
on the last version

# Issues:
The game wont start

# Log:
There is no log

# Screenshot(s):
![]http://prntscr.com/sozfgh
# Labels:
(recommended labels)
state-nothing

**Comment by Mezahhh** [comment]
#1023

**Comment by Margen67** [comment]
Duplicate of #1023
