### ISSUE TITLE
4B4E07D1 - Rumble Roses XX

### ISSUE THREAD

**Issue by Spyro0210** [xenia-project/game-compatibility#1590]
(1) The game occasionally freezes.

(2) There are some graphical glitches happening: Occasionally a part of the mesh from the fighters body randomly distorts to a point. This glitch is visible for one frame and then disappears. This glitch happens many times in a minute. It is visible during fights and the status screen in the locker.

**Comment by illusion0001** [comment]
Duplicate of #770
