### ISSUE TITLE
4D5307D2 - Kameo: Elements of Power

### ISSUE THREAD

**Issue by Vezok17** [xenia-project/game-compatibility#1594]
[Marketplace](http://marketplace.xbox.com/...)

Tested on https://github.com/xenia-project/xenia/commit/68dd8180/

# Issues:
Xenia opens the game menu but i can't create a game save and when I try to play without saving, Xenia freezes and don´t proceed  

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/4893088/xenia.zip)

# Screenshot(s):
Screenshot 1: Xenia creates a save game with that stange name and don't lets to play it
![1](https://user-images.githubusercontent.com/68031546/86967089-744b2f80-c16a-11ea-9da1-36a84a146200.PNG)

Screenshot 2: The moment when Xenia freezes
![2](https://user-images.githubusercontent.com/68031546/86967096-757c5c80-c16a-11ea-9f33-a9728112547d.PNG)

# Labels:
state-title

**Comment by Triang3l** [comment]
Please move your report to #173.
