### ISSUE TITLE
5841091C - Meteos Wars

### ISSUE THREAD

**Issue by ghost** [xenia-project/game-compatibility#1597]
[Marketplace](https://marketplace.xbox.com/en-us/Product/METEOS-WARS/66acd000-77fe-1000-9115-d8025841091c)

Tested on [xenia-project/xenia@`b84239d`](https://github.com/xenia-project/xenia/commit/b84239d507aa09c9b0077b69cb1b38f431b844f1)

### Issues:
Game constantly crashes, and deals with screen tears even when Vsync is on.

### Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/4908782/xenia.zip)

### Screenshot(s):
![xenia](https://user-images.githubusercontent.com/68193876/87250362-41d35800-c432-11ea-9af0-66b67e85b5b8.JPG)

### Specs:
CPU - Intel Core i7-7700HQ CPU @ 2.80GHz 2.80 GHz
GPU - GTX 1050ti 4GB
RAM - 16.0 GB
Windows 10 x64

### Labels:
state-gameplay

**Comment by Sleepy93** [comment]
I think this issue [@1765](https://github.com/xenia-project/game-compatibility/issues/1765) is more relevant than this.
