### ISSUE TITLE
584107F1 - Feeding Frenzy

### ISSUE THREAD

**Issue by benvanik** [xenia-project/game-compatibility#16]
[Xbox Marketplace](http://marketplace.xbox.com/en-US/Product/Feeding-Frenzy/66acd000-77fe-1000-9115-d802584107f1)

v1.0.1.0

Tested against benvanik/xenia@ddbab8216954074a3f93536e7a9fb28ecdca8956.

* [ ] No input once in game
* [ ] Super slow frame times (waiting?)

**Comment by Razzile** [comment]
https://github.com/xenia-project/game-compatibility/issues/118 is more relevant now
