### ISSUE TITLE
Magna Carta 2 crash Abazet Port bug

### ISSUE THREAD

**Issue by yukinomose** [xenia-project/game-compatibility#1612]
https://marketplace.xbox.com/en-us/Product/Magnacarta2/66acd000-77fe-1000-9115-d8024e4d080b

Tested on https://github.com/xenia-project/xenia/commit/1708a24881fa2f7c4009162acc49252af95e0383

# Issues:
the game crash to Abazet Port - message the guest has crashed, Xenia has now paused itself. A crash dump has been written into the log"

# Log:
[xenia log.zip](https://github.com/xenia-project/game-compatibility/files/5079275/xenia.log.zip)

# Screenshot(s):
![crash](https://user-images.githubusercontent.com/69730119/90319385-e10ad400-df37-11ea-9e09-838a010ab067.png)

# Labels:
(recommended labels)

state-gameplay

**Comment by Etokapa** [comment]
#721

**Comment by omidus** [comment]
is there a fix for this?
