### ISSUE TITLE
4B4E0823 - Silent Hill Downpour

### ISSUE THREAD

**Issue by Falyandar** [xenia-project/game-compatibility#1639]
water disappears, game runs very good just that is a little annoying how to fix?

**Comment by Sterophonick** [comment]
https://github.com/xenia-project/game-compatibility/issues/301

Make sure you provide screenshots, the emulator version you ran it on, and a log.

**Comment by Falyandar** [comment]
ok where would i get the log from?

**Comment by Sterophonick** [comment]
It's rhe "xenia.log" file the is created when running a game. Check in the game directory.

**Comment by Falyandar** [comment]
ok ill see if i can get that stuff u mentioned

**Comment by Falyandar** [comment]
ok here is the picture 
![84516ea4de3a19629a96c4682c7c0f84](https://user-images.githubusercontent.com/73209396/96669147-3c838480-1322-11eb-93c9-93794455a33e.jpg) and here is my log file 
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/5413072/xenia.zip) and the version im running is from jun 2 of 2020 i did try both the latest version and this version but both do the same problem with the water

**Comment by Sterophonick** [comment]
You need to put that in the issue I posted above, and not the date, the
commit code. It's shown in the emulator title bar.

**Comment by illusion0001** [comment]
Invalid issue and please discuss in https://github.com/xenia-project/game-compatibility/issues/301 as mentioned above.

**Comment by Margen67** [comment]
Duplicate of #301
