### ISSUE TITLE
54510890 - WWE '12

### ISSUE THREAD

**Issue by kye-l** [xenia-project/game-compatibility#1655]
[Marketplace](https://marketplace.xbox.com/en-GB/Product/WWE-12/66acd000-77fe-1000-9115-d80254510890)

Tested on https://github.com/xenia-canary/xenia-canary/commit/966b465cb34cf431845ff96767282cd0bec70cf8

# Issues:
Game playable in menus & creation suite but crashes upon loading into an actual match no matter what.

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/5610561/xenia.zip)

# Screenshot(s):
![)](https://user-images.githubusercontent.com/75166822/100515447-392ab680-3174-11eb-9880-539d4ee5e4b7.png)

# Labels:
state-title - Works just fine in menus, at a solid 60FPS

state-crash-guest - crashes ingame

**Comment by Nighterlev** [comment]
This is a canary test and should be submitted here https://github.com/xenia-canary/game-compatibility/issues
Not on the master page, please fix and remove.

**Comment by chincheeke** [comment]
good
