### ISSUE TITLE
4D5309C9 - Forza Horizon

### ISSUE THREAD

**Issue by XxXSergioGamerXxX** [xenia-project/game-compatibility#1696]
https://marketplace.xbox.com/en-US/Product/Forza-Horizon/66acd000-77fe-1000-9115-d8024d5309c9

Tested on https://github.com/xenia-project/xenia/commit/c218d6dc10231fc25636b16e3e7659bac55365da on Sep 21 2020

# Issues:
Running works, but with fps drops, also apparently everything that is grass is invisible in the game, either in mountains or on the side of the road

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/5851406/xenia.zip)

# Screenshot(s):
![Imagen1](https://user-images.githubusercontent.com/77802413/105396788-098dad00-5bff-11eb-80ee-4ffce51d3ad3.jpg)
![Imagen2](https://user-images.githubusercontent.com/77802413/105396792-0abeda00-5bff-11eb-8463-f116730764a3.jpg)
![Imagen3](https://user-images.githubusercontent.com/77802413/105396774-05fa2600-5bff-11eb-81a1-8085e8afcbb7.jpg)
![Imagen4](https://user-images.githubusercontent.com/77802413/105396779-072b5300-5bff-11eb-81aa-98e3ece57b83.jpg)
![Imagen5](https://user-images.githubusercontent.com/77802413/105396784-085c8000-5bff-11eb-81d4-3499ce7bffec.jpg)
![Imagen6](https://user-images.githubusercontent.com/77802413/105397588-07781e00-5c00-11eb-81bc-98eee34312fc.jpg)
![Imagen7](https://user-images.githubusercontent.com/77802413/105397750-37272600-5c00-11eb-8f19-59e8c993d555.jpg)

# Labels:
gpu-drawing-corrupt | gpu-shader-errors | gpu-slow | state-gameplay

**Comment by Gliniak** [comment]
Duplicate: https://github.com/xenia-project/game-compatibility/issues/509
