### ISSUE TITLE
D8025752 - Looney Toons: ACME Arsenal

### ISSUE THREAD

**Issue by deadair3210** [xenia-project/game-compatibility#171]
[Marketplace](http://marketplace.xbox.com/en-US/Product/Looney-Tunes-AA/66acd000-77fe-1000-9115-d802575207d2)

Tested on xenia-project/xenia#417

# Issues:
When launched, plays a bit of sound(glitched?), and does nothing else, no picture.

# Log:
https://gist.github.com/deadair3210/d6c51616f0a071d3aa99

# Labels:
state-nothing

**Comment by Prism019** [comment]
This issue is a clone of #746
The title id in the title is incorrect, as the log says 575207D2.
