### ISSUE TITLE
58410B55 - Who Wants To Be A Millionaire Special Editions

### ISSUE THREAD

**Issue by Rhystic1** [xenia-project/game-compatibility#1715]
[Marketplace](https://marketplace.xbox.com/en-GB/Product/Who-Wants-To-Be-A-Millionaire-Special-Editions/66acd000-77fe-1000-9115-d80258410b55)

Tested on https://github.com/xenia-project/xenia/commit/a577a4ae8bd4955587202d27bf2d38ea0c2aa4f9

# Issues:
The game will start, show the first few developer/publisher logos, then crash.

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/6026240/xenia.zip)

# Screenshot(s):
![Screenshot 2021-02-23 010953](https://user-images.githubusercontent.com/3988944/108790220-14c45780-7574-11eb-8685-841e7cbc9947.png)
![Screenshot 2021-02-23 011045](https://user-images.githubusercontent.com/3988944/108790229-1b52cf00-7574-11eb-86ad-1803a14f855d.png)
![Screenshot 2021-02-23 011054](https://user-images.githubusercontent.com/3988944/108790242-2279dd00-7574-11eb-899d-53a39184dea6.png)

# Labels:

tech-engine-unreal
state-intro

**Comment by illusion0001** [comment]
Submit a report with correct version of Xenia. Only main branch of xenia is allowed on this compatibility report.
