### ISSUE TITLE
UFC undisputed 3 - Issues not loading graphics in the match

### ISSUE THREAD

**Issue by MSIDKING** [xenia-project/game-compatibility#1755]
Game name : UFC undisputed 3
**Issues**:Everything menu and characters but then you want to load to the match or training its just black screen with sound it doesn't freeze its just a black screen
![ufc bug 1](https://user-images.githubusercontent.com/83833889/117497996-dbe82c00-af81-11eb-815f-13045e2a98ef.png)
![ufc bug 2](https://user-images.githubusercontent.com/83833889/117497998-dc80c280-af81-11eb-929b-e369a1ca19be.png)

**Comment by Margen67** [comment]
Duplicate of #1081
