### ISSUE TITLE
58411F7 - Minecraft: Xbox 360 Edition | TU Not Applying

### ISSUE THREAD

**Issue by Wikalaxy** [xenia-project/game-compatibility#1757]
Hello! I am a very new user of Xenia.
I have installed Minecraft: Xbox 360 Edition on Xenia Canary. I have edited the config so it plays the full game and have properly (AFAIK) added a new TU. However, the game still launches on TU1.
Any help would be great! Thanks.

**Comment by somegamer2001** [comment]
i know this is closed but i have the same issue lol
