### ISSUE TITLE
Minecraft Xbox 360 Edition

### ISSUE THREAD

**Issue by sanikdah** [xenia-project/game-compatibility#1759]
Specs: Intel Core i5-7400, 16GB RAM, AMD Radeon RX 560, Minecraft TU 74
When creating a new world, it takes a long time on the final bit of the bar of the "Loading spawn area" portion of the world creation, after a while it comes up with an error saying that an error has occurred and that Minecraft will now exit back out to the main menu (image of that attached).  Then it asks me whether I want to save changes to the world or not, no matter which button I press the whole game crashes (the error from xenia is also attached).  Also attached is the log that xenia made.
![image](https://user-images.githubusercontent.com/72118300/117738862-da9d4600-b1b1-11eb-8800-04999e3934ac.png)
![image](https://user-images.githubusercontent.com/72118300/117738871-dec96380-b1b1-11eb-8096-28a36dc8f30d.png)
[xenia log of minecraft crashing when creating and loading a world.log](https://github.com/xenia-project/game-compatibility/files/6455587/xenia.log.of.minecraft.crashing.when.creating.and.loading.a.world.log)

**Comment by Margen67** [comment]
Duplicate of #29
