### ISSUE TITLE
So when I try to play resident evil revelations 2 the moment I start the game it doesn’t load.

### ISSUE THREAD

**Issue by jillv46** [xenia-project/game-compatibility#1796]
So when I try to play resident evil revelations 2 the moment I start the game it doesn’t load. Revelations 1 works fine but revelations 2 doesn’t work. Why is this happening? Here’s a pic of what I get when starting the game![image](https://user-images.githubusercontent.com/29643271/126164873-bfa8c9de-bad8-43df-b432-d9aba227dbc7.jpeg)

**Comment by Margen67** [comment]
Duplicate of #38
