### ISSUE TITLE
584109C2 - Perfect Dark Model/texture noise

### ISSUE THREAD

**Issue by dclem2** [xenia-project/game-compatibility#1798]
Has there been a fix to this texture-noise issue? I am running xenia (canary) (000052CC Build: canary_experimental)
![shot0](https://user-images.githubusercontent.com/27931561/126227910-a3f3c0d7-9c98-470c-bb16-8297993bec6c.png)
![shot1](https://user-images.githubusercontent.com/27931561/126227925-8b534fc8-9246-4fc8-a0d1-ed9dfd7c17a4.png)

**Comment by Margen67** [comment]
Duplicate of #316
