### ISSUE TITLE
DRAGON BALL Z BATLLE OF Z XENIA

### ISSUE THREAD

**Issue by JESCAREN0107** [xenia-project/game-compatibility#1800]
4E4D0860 - Dragon Ball Z Battle of Z
When the game starts, after the developer logo credits are finished, Xenia stops. Most common error: "Guest has failed. Xenia has now stopped. A memory dump has been written to the registry." WILL YOU HELP ME IN MY PROBLEM?

**Comment by Margen67** [comment]
Duplicate of #871
