### ISSUE TITLE
4541096D - SSX (Deadly Descents)

### ISSUE THREAD

**Issue by Jamcdonald120** [xenia-project/game-compatibility#1815]
[Marketplace](https://marketplace.xbox.com/en-us/Product/SSX/66acd000-77fe-1000-9115-d8024541096d)

Tested on https://github.com/xenia-project/xenia/commit/a6954aced397ea1846379dbb48571a76637dadce

# Issues:
In the Antarctic Deadly Descent/Griff Race the solar powered heater acts like the player is perpetually in the shade even when in the sun.

# Labels:
state-gameplay

**Comment by Triang3l** [comment]
Please check if the entry for the game already exists before creating a new one. I have moved your report to the game's entry. Also specific instances of incorrect behavior should be reported in the tracker entry for the whole game, not in separate issues.

**Comment by Margen67** [comment]
Duplicate of #64
