### ISSUE TITLE
Naruto the Broken Bond crashing issues. 

### ISSUE THREAD

**Issue by Ora0001** [xenia-project/game-compatibility#1840]
GAME TITLE ID - Naruto the Broken Bond 55530825
Issue: Game crashes 5 minutes into the Story Mode game mode. On the English voice acting/ dub of the game it does not work at all. If you switch to Japanese voices It works for 5 minutes and then It crashes again.
Zip file for logs:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/7278105/xenia.zip) Hopefully I did it right.

**Comment by Margen67** [comment]
Duplicate of #416
