### ISSUE TITLE
Deathspank save issues 

### ISSUE THREAD

**Issue by Bryguygames** [xenia-project/game-compatibility#1852]
[Marketplace](http://marketplace.xbox.com/...)

Tested on https://github.com/xenia-project/xenia/commit/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# Issues:
(state of the game) it has save issues in game sound glitches 

# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here (replacing this text).

# Screenshot(s):
![](Screenshot URL)

# Labels:
(recommended labels)

**Comment by Bryguygames** [comment]
![A5442440-6F53-4E24-A8E0-CF37DF21C327](https://user-images.githubusercontent.com/87958736/141230544-12b5feff-4433-4e55-b58f-fdf4e316ebdf.jpeg) here save issues

**Comment by Margen67** [comment]
#1897
