### ISSUE TITLE
58410a6f - deathspank

### ISSUE THREAD

**Issue by Bryguygames** [xenia-project/game-compatibility#1853]
![7DBF211D-528F-4A03-A4FE-5C20A26FCA0D](https://user-images.githubusercontent.com/87958736/142721636-03789d5b-7e40-4b71-9dc0-d753df695173.jpeg)

[Marketplace](http://marketplace.xbox.com/...)

Tested on https://github.com/xenia-project/xenia/commit/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# Issues: save data issues crash while in gameplay 
(state of the game)

# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here (replacing this text).

# Screenshot(s):
![](Screenshot URL)

# Labels:save issues game crashes whil enter gameplay 
(recommended labels)

**Comment by Margen67** [comment]
#1897
