### ISSUE TITLE
58410a6f - deathspank

### ISSUE THREAD

**Issue by Bryguygames** [xenia-project/game-compatibility#1854]
[Marketplace](http://marketplace.xbox.com/...)

Tested on https://github.com/xenia-project/xenia/commit/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# Issues:
Game intro plays well wehrn you press start save issues 

# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here (replacing this text).

# Screenshot(s):
![](Screenshot URL)

# Labels:

state-gameplay

**Comment by Margen67** [comment]
#1897
