### ISSUE TITLE
a software that will helping find comptablity problems 500x more quick possibly

### ISSUE THREAD

**Issue by ma8070322** [xenia-project/game-compatibility#1864]
gsgsgsgsg

[Marketplace](http://marketplace.xbox.com/...)

Tested on https://github.com/xenia-project/xenia/commit/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxsgsgsg

# Issues:
(state of the game)sgsgsgsgsg

hack your health so you dont die and then move 20x more quick in the game to complete the game quick
https://cheatengine.org/downloads.php

click enable speedhack and set the speedhack to any speed above 1
now you will move more quick through the game
the speedhack doesnt work then you(the creator of xenia)will have to find whats causeing

# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here (replacing this text).sgsgsgsg

# Screenshot(s):
![](Screenshot URL)sgsgsgsgsgs

# Labels:
(recommended labels)
sgsgsgsgsgsgsgs
sg

**Comment by Triang3l** [comment]
Software that will make your reports invalid 500x more quick. You must not submit anything to the compatibility tracker with non-default speed used at any moment during the game, or any memory or code patches. Also, this issue tracker is totally not the place for such kind of messages. And repeated posting will get you banned if you continue.

**Comment by ma8070322** [comment]
the software will make more posts 500x more important that any post on this website,this software could easily make xenia from 200 working to games in years to 700 working games in mounths
