### ISSUE TITLE
Call of Duty : Advanced Warfare Multiplayer

### ISSUE THREAD

**Issue by shadowbrony33** [xenia-project/game-compatibility#189]
boots but will crash after pressing start, farthest it got was adjusting brightness levels.

**Comment by Razzile** [comment]
could you follow the post template [here](https://github.com/xenia-project/game-compatibility)

**Comment by DrChat** [comment]
Need a log/whatever. Repost this with the proper format.

**Comment by Margen67** [comment]
#1020
