### ISSUE TITLE
56181H35 - Limbo Demo

### ISSUE THREAD

**Issue by heysehaven** [xenia-project/game-compatibility#191]
[Marketplace](http://marketplace.xbox.com/pt-BR/Product/LIMBO/66acd000-77fe-1000-9115-d802584109d1)
Test with EmuCr Xenia Git (2015/09/13)
loads and get in game with black screen only audio
[LOG](https://gist.github.com/heysehaven/fb787a9a544fdf7d17b3)

**Comment by gibbed** [comment]
https://github.com/xenia-project/game-compatibility/issues/503
