### ISSUE TITLE
5841097E - Battlefield 1943 Trial

### ISSUE THREAD

**Issue by heysehaven** [xenia-project/game-compatibility#192]
[Marketplace](http://marketplace.xbox.com/en-US/Product/Battlefield-1943/66acd000-77fe-1000-9115-d8025841097e)
Test with EmuCr Xenia Git (2015/09/13)
Audio sounds to be corrupted 
Menu game 
![menu](https://cloud.githubusercontent.com/assets/14338853/9996702/a0bd656e-605e-11e5-858f-0231557e7b17.PNG)
Tutorial loading 
![loding](https://cloud.githubusercontent.com/assets/14338853/9996724/bb6cb766-605e-11e5-8e9c-7877c04164fb.PNG)
Freezes when i push ready button 

![crashes when i push ready](https://cloud.githubusercontent.com/assets/14338853/9996747/d9754a20-605e-11e5-8857-a46c368610c9.PNG)

**Comment by DrChat** [comment]
Audio is corrupted because they're using an unknown XMA/XMA2 format. Someone with heavy experience in this stuff is going to have to look into the codec.

**Comment by elfogames** [comment]
@Razzile Audio is workine fine now

**Comment by Hotlipo** [comment]
The tutorial is now fully playable without a crash, sound works and the FPS are between 3-10, when you look to the sky its almost 30FPS. And the rest sees one on the Pictures. https://github.com/benvanik/xenia/commit/212cd6ee3dbfbf92d85785081e879d7e17b3de3c
![1](https://cloud.githubusercontent.com/assets/13397218/16363685/8053d16e-3bd2-11e6-9f0b-1299d688c246.JPG)
![2](https://cloud.githubusercontent.com/assets/13397218/16363688/8054db36-3bd2-11e6-8f25-658b0d480332.JPG)
![3](https://cloud.githubusercontent.com/assets/13397218/16363689/8054f22e-3bd2-11e6-919d-0f1d047093ff.JPG)
![4](https://cloud.githubusercontent.com/assets/13397218/16363686/80541732-3bd2-11e6-860d-79f5de559329.JPG)
![5](https://cloud.githubusercontent.com/assets/13397218/16363687/80546fac-3bd2-11e6-8b18-c7f19d55a9f4.JPG)

**Comment by SENSENuii** [comment]
https://youtu.be/pNG5U8a3C-w

**Comment by zumbuh** [comment]
I do not see gameplay, I just hear the game in the bg and see a black screen (with hud)

**Comment by somereallygoodname** [comment]
Performance is good on https://github.com/benvanik/xenia/commit/24baf58ae39b67f9c189db7542ea7a7f6d513d11. Graphical differences from the gameplay provided by Hotlipo could just be caused by the AMD gpu. Not sure yet. Audio is very buggy.

[Video](https://youtu.be/cjNMJR-FJLM)

**Comment by somereallygoodname** [comment]
stutters, some shadow bugs and audio doesn't always play but other than that it seems fine. Tested on https://github.com/xenia-project/xenia/commit/57e8f05234f2cf8ee29cffd3ab8fe57de38479b8 (D3D12)

[Video](https://youtu.be/avDNNQyh39k)

**Comment by Nighterlev** [comment]
Shouldn't this be closed..?  Trial and official are basically the same game. Same tutorials I'm pretty sure.
https://github.com/xenia-project/game-compatibility/issues/106
This one is older to.

**Comment by Margen67** [comment]
Duplicate of #106
