### ISSUE TITLE
46530002-Otogi: myth of demons 

### ISSUE THREAD

**Issue by vomitturtlerocket** [xenia-project/game-compatibility#1941]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch. (not MLBS/AlexVS/Canary/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xbox 360 Marketplace link

(https://www.xbox.com/en-US/games/store/otogi-myth-of-demons/9mz93mfg08sr)

### Xenia version

https://github.com/xenia-project/xenia/commit/.../

### Issues

Crashes on startup when loading the ISO file. No error message shows up. Tried loading a few times with the same result. 

### Log

[xenia.log](https://github.com/xenia-project/game-compatibility/files/8510400/xenia.log)

### Screenshots

it just crashes, so no screenshot

### Labels

 state-nothing

**Comment by Margen67** [comment]
This is an original Xbox game..
