### ISSUE TITLE
494707DB - Bullet Witch

### ISSUE THREAD

**Issue by Umit007** [xenia-project/game-compatibility#2007]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch. (not MLBS/AlexVS/Canary/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xenia version

https://github.com/xenia-project/xenia/commit/.../

### Issues

GeForce RTX 3060 Graphic card for Render and textures compatibility and some crash dump errors.

### Log

[Uploading xenia_master (1).zip…]()

### Screenshots

![Uploading Screenshot_1.png…]()

### Labels

gpu-shader-errors state-crash-OBSOLETE

**Comment by Margen67** [comment]
Duplicate of #1339
