### ISSUE TITLE
435607D5 - Crash Time

### ISSUE THREAD

**Issue by betelopson** [xenia-project/game-compatibility#2070]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch. (not MLBS/AlexVS/Canary/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xbox 360 Marketplace link

https://marketplace.xbox.com/en-gb/Product/Crash-Time/66acd000-77fe-1000-9115-d802524c07d1

### Xenia version

https://github.com/xenia-canary/xenia-canary/commit/1ae524a8d51f7de5df8d2a1f72d7a5fb0416e266

### Issues

Runs on Dx12 and Vulkan perfectly. Scales perfectly with Dx12, but it flickers.
Audio breaks at the second mission.

### Log

[xenia-canary.config.toml.zip](https://github.com/xenia-project/game-compatibility/files/11713075/xenia-canary.config.toml.zip)

### Screenshots

![Screenshot (73)](https://github.com/xenia-project/game-compatibility/assets/6606491/9fcc9450-edcb-4f38-8052-d8f4d2711ea7)
![Screenshot (75)(cropped)](https://github.com/xenia-project/game-compatibility/assets/6606491/2f876754-d3d1-42ee-965a-733d2a67b73a)
![Screenshot (76)](https://github.com/xenia-project/game-compatibility/assets/6606491/078be872-c722-432b-b602-b0095a60b742)
![Screenshot (77)](https://github.com/xenia-project/game-compatibility/assets/6606491/85df679b-ddab-4479-bb08-e0b475b191d4)

### Labels

apu-silent gpu-drawing-corrupt

**Comment by Margen67** [comment]
#2071
