### ISSUE TITLE
game crashes all time toy story 3

### ISSUE THREAD

**Issue by strqightlines** [xenia-project/game-compatibility#2081]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch. (not MLBS/AlexVS/Canary/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xbox 360 Marketplace link

https://marketplace.xbox.com/en-US/Product/Toy-Story-3/66acd000-77fe-1000-9115-d802425607e5?purchase=1&purchaseid=66acd000-77fe-1000-9115-d802425607e5

### Xenia version

https://github.com/xenia-project/xenia/commit/.../

### Issues

crashes when i start de game

### Log

toy story 3 crash when i play the game

### Screenshots

a

### Labels

estado-crash-guest

**Comment by Margen67** [comment]
Duplicate of #369
