### ISSUE TITLE
4E4D07E5 - DW:Gundam

### ISSUE THREAD

**Issue by KhaosThoeryy** [xenia-project/game-compatibility#2112]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch. (not MLBS/AlexVS/Canary/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xbox 360 Marketplace link
https://marketplace.xbox.com/en-us/Product/DW-GUNDAM/66acd000-77fe-1000-9115-d8024e4d07e5

### Xenia version

https://github.com/xenia-project/xenia/commit/f6b5424

### Issues

Crashes at Start Screen

### Log

n/a

### Screenshots

n/a

### Labels

state-crash-host

**Comment by Margen67** [comment]
Xenia Canary issue: https://github.com/xenia-canary/game-compatibility/issues/213
