### ISSUE TITLE
445007FF -  マージャン★ドリームクラブ

### ISSUE THREAD

**Issue by benvanik** [xenia-project/game-compatibility#22]
[Marketplace](https://marketplace.xbox.com/ja-JP/Product/%E3%83%9E%E3%83%BC%E3%82%B8%E3%83%A3%E3%83%B3-%E3%83%89%E3%83%AA%E3%83%BC%E3%83%A0%E3%82%AF%E3%83%A9%E3%83%96/66acd000-77fe-1000-9115-d802445007ff)
English/translated title: Mahjong Dream Club

v3.0.0.0

Tested against benvanik/xenia@ddbab8216954074a3f93536e7a9fb28ecdca8956.
- [ ] Draws RGB quad

May be progressing, but impossible to tell.

**Comment by Margen67** [comment]
Superseded by #1327.
