### ISSUE TITLE
468328E5 - Jet Set Radio Trial

### ISSUE THREAD

**Issue by heysehaven** [xenia-project/game-compatibility#246]
[Marketplace](http://marketplace.xbox.com/en-US/Product/Jet-Set-Radio/66acd000-77fe-1000-9115-d80258411247)

Tested on EmuCr Xenia Git (2015/11/12) [xenia-project/xenia@3d2a5b249555304818edb413c7a3b3bf697ca7be?]

# Issues:
Gets ingame with a lot of graphical issues.

# Video:
https://youtu.be/BzBcVBNxh9Y

# Labels:
state-gameplay, gpu-corrupt-drawing

**Comment by bdeimos** [comment]
Might be same thing as #204

**Comment by Margen67** [comment]
Useless EmuCr build version specified, no log, and video is gone.
