### ISSUE TITLE
FIFA world cup 2014 Brazil

### ISSUE THREAD

**Issue by xuliongamer** [xenia-project/game-compatibility#254]
the game start perfect, but crash in the loading match

video: https://www.youtube.com/watch?v=Wv8xCZ0q0XI

**Comment by Razzile** [comment]
already posted https://github.com/xenia-project/game-compatibility/issues/86 should update that one instead

**Comment by xuliongamer** [comment]
menu + 

video: https://www.youtube.com/watch?v=Wv8xCZ0q0XI
