### ISSUE TITLE
454109D4 - 2014 FIFA World Cup Brazil

### ISSUE THREAD

**Issue by RoySenpai** [xenia-project/game-compatibility#263]
[Marketplace] (http://marketplace.xbox.com/en-US/Product/EA-SPORTS-2014-FIFA-World-Cup-Brazil/66acd000-77fe-1000-9115-d802454109d4)

Test with EmuCR-Xenia-20151126.

## Notice
This IS NOT THE DEMO! This is the FULL VERSION of the game.

## Issues
Able to enter the menu and start a match, then it crashes.
Audio extrmly lags (Garbage), but the intro audio don't lag
GPU draw is corrupted when in match.
Sometimes the Xbox 360 controller vibrates violencely when the match starts (Need to disconnect the controller, closing xenia didn't stop the vibrations)

Tags: state-menus, gpu-corrupt-draw, audio-garbage, xam-input-problems

## Video
[Video] (https://www.youtube.com/watch?v=BiOcsXAYhEc)

## Log
[Compressed Log] (https://mega.nz/#!JhQEUQiB!ZbxAGE2fQVJ8XiDKggb4yqJ_VNtOZJJpNyRyS-l-WhA) - Unpacked size 302MB

**Comment by Razzile** [comment]
why does every person in the world have to post a log for this game, see https://github.com/xenia-project/game-compatibility/issues/86
