### ISSUE TITLE
4D5389D8 - Halo Reach Demo

### ISSUE THREAD

**Issue by Ichigo14** [xenia-project/game-compatibility#307]
[Xbox Marketplace](http://marketplace.xbox.com/en-US/Product/Halo-Reach/66acd000-77fe-1000-9115-d8024d53085b)

![haloreach1](https://cloud.githubusercontent.com/assets/16140062/11758602/d792d682-a07d-11e5-82e3-c7a6cf0ed182.jpg)

intro and reaches menus like here https://github.com/xenia-project/game-compatibility/issues/52

**Comment by Razzile** [comment]
has this not already been submitted in https://github.com/xenia-project/game-compatibility/issues/52?
