### ISSUE TITLE
45418897 - Left 4 Dead Demo

### ISSUE THREAD

**Issue by Gh0stblade** [xenia-project/game-compatibility#31]
Tested with: https://github.com/benvanik/xenia/commit/6d4d1db3106028cce6e28b5cb099324e146a7a25

You can hear audio for the introduction developer video but there is nothing displayed.
It goes to a load-screen to load the title screen then crashes but the background picture is all displayed fine.

**Comment by DrChat** [comment]
Closed: Use #89 instead.
