### ISSUE TITLE
Naruto - Rise of a Ninja 

### ISSUE THREAD

**Issue by Baboulinet123** [xenia-project/game-compatibility#325]
Hi,

 Tested on the latest build (14/12/15)

Log : http://puu.sh/lVjXf/5fb2d4e7ea.log

Got a black screen after the intro.

**Comment by Razzile** [comment]
https://github.com/xenia-project/game-compatibility/issues/131

**Comment by SakataGintokiYT** [comment]
-How to game run  
Extrat ISO  (Software :  360mpGui v1.3.0.1 )
Delete:
-Ubisoft.bik 
-U.bik
-LOGO_CORPO_US.bik
-LOGO_CORPO_EMEAbik

**Comment by Baboulinet123** [comment]
Doesn't work. Plus, I don't have U.bik in the files, that may be what's causing the problem.

**Comment by SakataGintokiYT** [comment]
No need to remove  U.bik

**Comment by Baboulinet123** [comment]
Hmmm...I tried without these files, nothing happened. Only a black screen. Should I wait more than 1 min before getting something on the screen ?

**Comment by TrickyCloseCombat** [comment]
How can i remove those files?
