### ISSUE TITLE
545407F2 - GTA IV

### ISSUE THREAD

**Issue by Kattus** [xenia-project/game-compatibility#353]
[Marketplace](http://marketplace.xbox.com/en-US/Product/GTA-IV/66acd000-77fe-1000-9115-d802545407f2)
Crashes straight away

Tested on benvanik/xenia@82ddd0430fe3792e8ce6e23dea161e5832b4f5f8
[Log output](https://gist.github.com/Kattus/cfc0b9bfe97b8c850b4e)

state-crash

**Comment by Razzile** [comment]
still, not far off PC port :P

**Comment by Kattus** [comment]
As of benvanik/xenia@82ddd0430fe3792e8ce6e23dea161e5832b4f5f8 it shows a "The guest has crashed." dialog instead of flat out crashing, log output stays 99% the same though.

**Comment by Tomasak** [comment]
http://i.imgur.com/cAHS0B5.png
Works very slow, 3D graphics rendered very badly
tested on b696c645f51c435abb21a83369e59d8426504e03
(https://github.com/benvanik/xenia/commit/b696c645f51c435abb21a83369e59d8426504e03)

**Comment by jc1999** [comment]
It's like Mafia II :O

**Comment by elfogames** [comment]
nice progress on rockstar games

**Comment by theoldsport** [comment]
Lol, I'm grabbing a 360 copy of this asap and playing it to the end!

**Comment by Kattus** [comment]
How are you guys getting this to run? running it on the same build as @Tomasak and the guest just crashes.

**Comment by Razzile** [comment]
closing in favour of https://github.com/xenia-project/game-compatibility/issues/427
