### ISSUE TITLE
4B5607E4 - NINJA GAIDEN 3 Razor‘s Edge

### ISSUE THREAD

**Issue by Myoko** [xenia-project/game-compatibility#360]
http://marketplace.xbox.com/en-US/Product/NINJA-GAIDEN-3-RE/66acd000-77fe-1000-9115-d8024b5607e4

Tested on EmuCR-Xenia-20151220.
now i can see main menu press A, i get saved games tips! and nothing happend.

![picture2015-12-21_200855](https://cloud.githubusercontent.com/assets/3013386/11930599/ee227700-a81f-11e5-8afa-e37052c6d243.png)

LOG
http://www20.zippyshare.com/v/YqEKxpKq/file.html

**Comment by Razzile** [comment]
https://github.com/xenia-project/game-compatibility/issues/299
