### ISSUE TITLE
555308CA - Far Cry 4

### ISSUE THREAD

**Issue by Kattus** [xenia-project/game-compatibility#364]
[Marketplace](http://marketplace.xbox.com/en-US/Product/Far-Cry-4/66acd000-77fe-1000-9115-d802555308ca)
![Screenshot](http://i.imgur.com/G6oEBQa.jpg)
Tested on benvanik/xenia@82ddd0430fe3792e8ce6e23dea161e5832b4f5f8

Crashes when trying to save game data.
[Log output](https://gist.github.com/Kattus/89da7e0cd397d1313d18)

state-title

**Comment by jc1999** [comment]
It's a black screen but you can press the A button and it tries to install and then it crashes
Log: 
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/322504/xenia.zip)
