### ISSUE TITLE
MX vs ATV: Alive

### ISSUE THREAD

**Issue by xuliongamer** [xenia-project/game-compatibility#372]
the game loads up to the start of the race, there is unplayable: /

![xenia_2015_12_25_23_20_11_740](https://cloud.githubusercontent.com/assets/16033908/12004804/b7c6dcee-ab5f-11e5-9412-6184aee6c2c8.jpg)
![xenia_2015_12_25_23_20_21_321](https://cloud.githubusercontent.com/assets/16033908/12004805/b7e5886a-ab5f-11e5-94d6-af3d10a7ee6e.jpg)
![xenia_2015_12_25_23_20_36_390](https://cloud.githubusercontent.com/assets/16033908/12004807/b81adba0-ab5f-11e5-8fec-1d45aa8f3879.jpg)
![xenia_2015_12_25_23_20_47_689](https://cloud.githubusercontent.com/assets/16033908/12004806/b80298ec-ab5f-11e5-83b4-00581092b300.jpg)
![xenia_2015_12_25_23_20_59_001](https://cloud.githubusercontent.com/assets/16033908/12004808/b82db2de-ab5f-11e5-8f8d-d8d0a9739261.jpg)
![xenia_2015_12_25_23_21_05_246](https://cloud.githubusercontent.com/assets/16033908/12004810/b83689cc-ab5f-11e5-9f09-8afe74ff3403.jpg)
![xenia_2015_12_25_23_21_39_848](https://cloud.githubusercontent.com/assets/16033908/12004809/b82ff5a8-ab5f-11e5-96a4-5bae14ad2e5e.jpg)

**Comment by xuliongamer** [comment]
state: loaded

**Comment by Razzile** [comment]
could you follow the log format [here](https://github.com/xenia-project/game-compatibility/) please? will reopen when fixed
