### ISSUE TITLE
Star Ocean 4 into works menus works no render after 

### ISSUE THREAD

**Issue by alexis23ange** [xenia-project/game-compatibility#388]
i hope this helps you 
[xenia.log.txt](https://github.com/xenia-project/game-compatibility/files/92164/xenia.log.txt)

**Comment by alexis23ange** [comment]
https://www.youtube.com/watch?v=PnjQD5xi6AM here is it in action

**Comment by Razzile** [comment]
can you follow the log format [here](https://github.com/xenia-project/game-compatibility/) please. I'll reopen issue when the format is correct :P

**Comment by alexis23ange** [comment]
you guys need a better way of doing things

**Comment by Razzile** [comment]
the whole point of the format is for [this to work](http://xenia.jp/compatibility/)
