### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by jc1999** [xenia-project/game-compatibility#402]
Hey, hope it's ok I help a little with this issue 

Game loads and screen is still black with audio it loads to the splash screen (That is also black) 

I'll add a screenshot I couldn't upload the log file cos I din't seem to get the compressing right

![blopsiiiscreen360](https://cloud.githubusercontent.com/assets/16037160/12538132/ac276faa-c2d1-11e5-8671-ea16d1bba8be.PNG)

**Comment by benvanik** [comment]
This should be attached to an existing issue, not a new one.

**Comment by Razzile** [comment]
@benvanik beat me to it by seconds 😐
