### ISSUE TITLE
4E4D0846- Dragon Ball Z: Ultimate Tenkaichi

### ISSUE THREAD

**Issue by SakataGintokiYT** [xenia-project/game-compatibility#412]
@Razzile 

Xbox Marketplace : http://marketplace.xbox.com/pl-PL/Product/Dragon-Ball-Z-UT/66acd000-77fe-1000-9115-d8024e4d0846

Xenia {2016.06.21}  
-Build : e95a08f
##### Labels:

-Menu

<img src="http://www.fotoszok.pl/upload/7c3d27ed.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/91c3ffd3.jpg" alt="Fotoszok.pl" />

**Comment by DrChat** [comment]
@SakataGintokiYT Please stop tagging us in your issues.

**Comment by SakataGintokiYT** [comment]
yep -____-

**Comment by Razzile** [comment]
what is this even meant to be labeled with?

**Comment by Kattus** [comment]
state-crash by the looks of it

**Comment by SakataGintokiYT** [comment]
Labels:
-Menu
