### ISSUE TITLE
41560914 - Call of Duty Advanced Warfare

### ISSUE THREAD

**Issue by shadowbrony33** [xenia-project/game-compatibility#447]
# Xbox Marketplace Link

http://marketplace.xbox.com/en-US/Product/COD-Advanced-Warfare/66acd000-77fe-1000-9115-d80241560914
# Xenia Build

https://github.com/benvanik/xenia/commit/d5865740e27b7f4059aae492626db37bac44b0e
# Issues:

Too many to list but mainly graphical
# Log:

https://mega.nz/#!G1MQQQSB!E4whs1L4ZOnQcGqLArTiZoXKMUsq-f3NSxAkBcWrvg4
# Screenshot(s):

http://imgur.com/a/Y9qd0
# Notes

Can only get gameplay when running the default_mp.xex instead of the default.xex.
# Labels:

video-garbage
state-gameplay
gpu-slow
gpu-corrupt-drawings
gpu-shader-errors

**Comment by spectrumm** [comment]
Ingame!! woop woop.
Playable, not optimal at all.n 30fps with drops down to 0.

1.0.987, Vulkan.
![screenshot_47](https://user-images.githubusercontent.com/23747820/29534940-4af7ba62-86b8-11e7-914f-60e6bd67b4db.png)
![screenshot_46](https://user-images.githubusercontent.com/23747820/29534941-4afa49c6-86b8-11e7-9496-01cb1b3da4a7.png)
![screenshot_45](https://user-images.githubusercontent.com/23747820/29534942-4afaae8e-86b8-11e7-9c4c-00d0a6e27766.png)
![screenshot_44](https://user-images.githubusercontent.com/23747820/29534943-4afaa218-86b8-11e7-9b20-02dae5c64800.png)
![screenshot_52](https://user-images.githubusercontent.com/23747820/29534944-4afc3128-86b8-11e7-939e-c4cbd5d7d589.png)
![screenshot_51](https://user-images.githubusercontent.com/23747820/29534945-4b0207ba-86b8-11e7-9460-603d726e498d.png)
![screenshot_50](https://user-images.githubusercontent.com/23747820/29534948-4b17d8ce-86b8-11e7-90d9-f44a7c7fb52a.png)
![screenshot_49](https://user-images.githubusercontent.com/23747820/29534947-4b16ed74-86b8-11e7-98de-ce102b5da8bc.png)
![screenshot_48](https://user-images.githubusercontent.com/23747820/29534946-4b14ec2c-86b8-11e7-9661-cbcabc5d2ebd.png)

**Comment by shadowbrony33** [comment]
@spectrumm It's been in-game since this post was made.

**Comment by Margen67** [comment]
#1020
