### ISSUE TITLE
415687EE - Call of Duty 3 Demo

### ISSUE THREAD

**Issue by jc1999** [xenia-project/game-compatibility#457]
[Marketplace](http://marketplace.xbox.com/nb-NO/Product/Call-of-Duty-3/66acd000-77fe-1000-9115-d802415607e1)

Tested on (EmuCR-Xenia-20160619-x64)
# Issues:

(It's a black screen)
# Log:

[Log file]([Uploading xenia.zip…])
# Screenshot(s):

![](Screenshot URL)
# Labels:

(Crash?)

**Comment by jc1999** [comment]
With a little more testing it loads on the Vulkan build (EmuCR-Xenia-vulkan-20160613-x64)

**Comment by Margen67** [comment]
Have you tried the Appveyor builds?

**Comment by jc1999** [comment]
No I haven't. Can you link me?

**Comment by MarioSonic2987** [comment]
Here: https://ci.appveyor.com/project/benvanik/xenia/build/artifacts

**Comment by jc1999** [comment]
Thank you!

**Comment by MarioSonic2987** [comment]
:)

**Comment by Snoobz** [comment]
Hello,

So I tried playing this game but it doesn't work, it loads forever. Do you guys have a solution? I used the latest update of Xenia available at the moment. 
Just in case, I'm using an ISO file is that okay? 

Thanks for the help!

**Comment by PersonalityPi** [comment]
Hasn't changed since. Still just sits on a blackscreen.

**Comment by lif3mau5** [comment]
Pls dev's, make this game compatible, it's a exclusive title only for console

**Comment by InwardHydra** [comment]
> Pls dev's, make this game compatible, it's a exclusive title only for console

There are other ways of playing this game, as it is available for Xbox, PS2, PS3, and Wii as well as Xbox 360, and if you look hard enough at thrift stores you can find copies, as I recently found a PS2 copy.
