### ISSUE TITLE
545408B8 - Grand Theft Auto: San Andreas

### ISSUE THREAD

**Issue by Kattus** [xenia-project/game-compatibility#468]
[Marketplace](http://marketplace.xbox.com/en-US/Product/Grand-Theft-Auto-San-Andreas/66acd000-77fe-1000-9115-d802545408b8)

Tested on benvanik/xenia@e95a08fc87a93567eaacf7175475fa921c9bc2d5

# Issues:
Doesn't do anything, blank screen.

# Log:
[Log file](https://gist.github.com/ddf331f0d38f7f41f6ba717858ad5212)

# Labels:
state-nothing

**Comment by TotalCaesar659** [comment]
It's duplicate of https://github.com/xenia-project/game-compatibility/issues/186
![1](https://cloud.githubusercontent.com/assets/14265316/16290748/95655b9e-3908-11e6-9a61-f13794cb0309.png)

**Comment by Kattus** [comment]
Sorry, I promise I did actually search, must've been too tired though.
