### ISSUE TITLE
Xenia Cant find Exe please help

### ISSUE THREAD

**Issue by Biggums** [xenia-project/game-compatibility#519]
I recently got the Xenia-master download but cant find its exe to run the emulator. I really would appreciate the help. Btw if anyone knows a link for a red dead redemption game for the emulator that would help a lot.

**Comment by Razzile** [comment]
not what this is for at all.

**Comment by Kattus** [comment]
You have to compile it yourself or find a pre-compiled build elsewhere, you'll also have to buy the game yourself.
