### ISSUE TITLE
42C67824 - Forza 4 GOTY (PAL)

### ISSUE THREAD

**Issue by voltagex** [xenia-project/game-compatibility#55]
benvanik/xenia@fc7695f

http://marketplace.xbox.com/en-AU/Product/Forza-Motorsport-4/66acd000-77fe-1000-9115-d8024d530910

Extracted ISO seems to start loading, as long as xenia's working directory is the same as where the game data is.

The UI then changes colour slightly (?) and no further progress is made
![untitled](https://cloud.githubusercontent.com/assets/159567/8376465/fcd6e53a-1c4a-11e5-832e-00187d17a9db.png)

**Comment by voltagex** [comment]
benvanik/xenia@720f8b0 - Audio, no video in intro video/s. Pressing A gets me to 
![xenia detached_720f8b0_may 1 2016 - forza motorsport 4 2_05_2016 8_44_27 pm](https://cloud.githubusercontent.com/assets/159567/14952775/bebb5f46-10a6-11e6-93ad-3b92175d77ad.png). 

Intro *audio* plays after skipping video but I haven't continued to see if anything else loads - log is already a gargantuan _1.2GB_ uncompressed!
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/244891/xenia.zip)

**Comment by Razzile** [comment]
https://github.com/xenia-project/game-compatibility/issues/442
