### ISSUE TITLE
Sonic Unleashed Demo

### ISSUE THREAD

**Issue by yugi1408** [xenia-project/game-compatibility#553]
When I press Start Game on Sonic Unleashed Demo, the game goes to the loading screen but then stays on the loading screen which is frozen, but the game still starts, you can tell because the music starts and when you press different buttons on the controller you can hear sonic making different sounds, just the screen stays as the loading screen and you can only make it so far before the xenia emulator crashes.
Please Fix This

**Comment by Razzile** [comment]
can you please follow the issue format? closing until it's fixed
