### ISSUE TITLE
Sonic The Hedgehog 2006

### ISSUE THREAD

**Issue by yugi1408** [xenia-project/game-compatibility#554]
Every time I Homing Attack (Not including onto rails), the game freezes or black screens, with the music still on, also sometimes when its a black screen it sometimes after a while puts you back at the beginning of the level, please fix this, oh and the graphics are not correct but over the course of this project they have improved
Also I don't understand half the stuff on the correct issue format and I can't find the files, also another problem is it won't let me press submit issue.

**Comment by yugi1408** [comment]
IMPORTANT:
Also I don't understand half the stuff on the correct issue format and I can't find the files, also another problem is it won't let me press submit issue.

**Comment by Razzile** [comment]
did you resubmit this because i closed the other one?
