### ISSUE TITLE
464F0802 - Terraria

### ISSUE THREAD

**Issue by TotalCaesar659** [xenia-project/game-compatibility#659]
[Marketplace](http://marketplace.xbox.com/en-US/Product/Terraria-Xbox-360-Edition/66acd000-77fe-1000-9115-d8025841128f)

Tested on (https://github.com/benvanik/xenia/commit/391b6e9bb772161ca9e99e247c2fe869c19ea745)

# Issues:
White screen only.

# Log:
[Log file](https://drive.google.com/file/d/0B7KpdfS_wYnZUUtESUdETG9KSGc/view)

# Screenshot(s):
![0000](https://cloud.githubusercontent.com/assets/14265316/20037022/7b098ab8-a429-11e6-88c3-e535f3208b70.jpg)

# Labels:
(state-nothing)

**Comment by Razzile** [comment]
https://github.com/xenia-project/game-compatibility/issues/199

**Comment by TotalCaesar659** [comment]
I didn't see it in compatibility list. Please, fix "**5841128F-** Terraria Trial" there.
