### ISSUE TITLE
Skate 3 Crash

### ISSUE THREAD

**Issue by ToxyPlayz** [xenia-project/game-compatibility#715]
[Marketplace](http://marketplace.xbox.com/...)
https://www.microsoft.com/en-US/store/p/Skate-3/BNKDKQXMXRR2

Tested on (xenia commit link)

# Issues:Crash after Intro
(state of the game)

# Log:
[Log file](https://gist.github.com/...)

# Screenshot(s):
![](Screenshot URL)
http://prntscr.com/dijvhd
# Labels:
(recommended labels)

state-crash

**Comment by tgsm** [comment]
#201
