### ISSUE TITLE
4E4D0817 - The Idol Master 2 (JP)

### ISSUE THREAD

**Issue by EAirPeter** [xenia-project/game-compatibility#722]
[Can't find on marketplace](http://bandainamcoent.co.jp/cs/list/idolmaster/im2/xbox/)

Tested on https://github.com/benvanik/xenia/commit/9f5abb02b7c23850440588c8ba6d6405527b625e

# Issues:
Crashes when loading.

# Log:
[Log file](https://raw.githubusercontent.com/EAirPeter/XeniaAbout/master/xenia.log)
The log file is too large for gist and preview.

# Screenshot(s):
![Capture.png](https://s24.postimg.org/6u9bno9ud/Capture.png)

# Labels:
state-crash

**Comment by Drive251** [comment]
duplicated with https://github.com/xenia-project/game-compatibility/issues/19
