### ISSUE TITLE
584111D6 - Bejeweled 3 Demo

### ISSUE THREAD

**Issue by voltagex** [xenia-project/game-compatibility#77]
benvanik/xenia@fc7695f
http://marketplace.xbox.com/en-AU/Product/Trial-Game-Bejeweled-3/f5ca827c-6a94-4d1b-930b-9bf9e6ee6fca?cid=SLink

Access violation
`xenia.exe!std::unique_ptr<xe::cpu::backend::Backend,std::default_delete<xe::cpu::backend::Backend> >::get() Line 1414 C++`

In Visual Studio I get a hang instead of a crash

[old logs removed]

**Comment by voltagex** [comment]
Playable but crashes after ~1m idle in game with benvanik/xenia@47a3ec083610c1e3284758a7952d203605549bd5 
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/1099477/xenia.zip)

**Comment by Razzile** [comment]
https://github.com/xenia-project/game-compatibility/issues/453
