### ISSUE TITLE
41560845 - Blur

### ISSUE THREAD

**Issue by theLMGN** [xenia-project/game-compatibility#777]
Not On Marketplace

Tested on 
https://github.com/benvanik/xenia/commit/afa52b532a33d234aa3cc51b0d91d34a60db5021

# Issues:
Intro only, Laggy, No video, Error messages

# Log:
[Log file](http://www.thelmgn.xyz/2017/06/xenia.log)

# Screenshot(s):
![](http://sx.thelmgn.com/2017/06/2017-06-24_13-49-23.png)

[Video](http://www.sx.thelmgn.com/2017/06/2017-06-24_13-38-20.mp4)

# Labels:
(recommended labels)

cpu-slow-start

audio-slow

cpu-jit

gpu-missing-drawing

state-intro

**Comment by theLMGN** [comment]
[On Actual Hardware](http://www.thelmgn.xyz/2017/06/2017-06-24_14-06-14.mp4)

**Comment by bdeimos** [comment]
Tested on (https://github.com/xenia-project/xenia/commit/ba7dc6b2d7187a233d7175c75994828b498bec58)

Crashes after intros that are just black screen.

(state-crash-guest gpu-missing-drawing)

[xenia.zip](https://github.com/xenia-project/game-compatibility/files/2173486/xenia.zip)
