### ISSUE TITLE
4D53085F - Viva Pinata Trouble in Paradise

### ISSUE THREAD

**Issue by Spinn10** [xenia-project/game-compatibility#778]
[Marketplace](http://marketplace.xbox.com/...)

Tested on (xenia commit link)

# Issues:
(state of the game)

# Log:
[Log file](https://gist.github.com/...)

# Screenshot(s):
![](Screenshot URL)

# Labels:
(recommended labels)

**Comment by Spinn10** [comment]
Hey everyone,
so I hope you can help me out with this.
When I first noticed there's an XBOX 360 emulator, I really got happy. I could finally play a game of my childhood on my PC. But my problem is, that when I start Xenia and select the game "Viva Pinata Trouble in Paradise" (It's a .iso-file) , it starts. But at a certain point, it says Xenia crashed. A few times when I tried it, there was a message from Windows, which said, "NVIDIA Kernel Driver ..." (or something like that) does not respond anymore. Can you help me out please?!

My PC contains:
GPU: GTX 1050 Ti (with lastest drivers) (OpenGL 4.5 compatible)
CPU: AMD Ryzen 5 1400 (should be AVX or AVX2 compatible)
8 GB RAM

I'll put the log in here. (I didn't figure out how to put a screenshot into this :/)

**Comment by Spinn10** [comment]
[xenia.txt](https://github.com/xenia-project/game-compatibility/files/1105542/xenia.txt)

**Comment by Spinn10** [comment]
That is the log.
Sorry for my inconvenience about using GitHub.

**Comment by Razzile** [comment]
https://github.com/xenia-project/game-compatibility/issues/292
