### ISSUE TITLE
Games which require xbox live sign in

### ISSUE THREAD

**Issue by cooperate** [xenia-project/game-compatibility#788]
Doritos Crash Course and Doritos Crash Course 2 get to titles but nothing happens when I press A to proceed.  On Doritos Crash Course 2 it asks for an Xbox Live sign-in but does nothing.  Is there a way to bypass mandatory Xbox Live sign-in games so I can see if these get to gameplay?

**Comment by Sleepy93** [comment]
Please modify your issue same as the sample of issues. 
https://github.com/xenia-project/game-compatibility/blob/master/README.md
also upload logs.

About Xbox Live Connectivity:

http://xenia.jp/roadmap/#xbox-live-connectivity

**Comment by XeClutch** [comment]
Xenia will either need to spoof the Xbox LIVE response so that the game thinks it's online or specifically write patches for each game to disable the always-online checks.
