### ISSUE TITLE
58410A54 - Radiant Silvergun

### ISSUE THREAD

**Issue by Sakimotor** [xenia-project/game-compatibility#802]
[Marketplace](http://marketplace.xbox.com/fr-fr/Product/Radiant-Silvergun/66acd000-77fe-1000-9115-d80258410a54)

Tested on https://github.com/benvanik/xenia/commit/aee5601c6895cb0f47c16d3f849b5ff56aae62ec

# Issues:
The Main Menu works fine, subtitles are appearing but there is still nothing ingame

Tested with OpenGL.

# Log:
[xenia.log](https://gist.github.com/Sakimotor/d57b11bb5fb59f4f7e4c0dccf62efb18)

# Screenshots:
![](http://i.imgur.com/GUVmT1m.png) 
![](http://i.imgur.com/mxQw0U4.png)
![](http://i.imgur.com/d9L6HTF.jpg)
# Labels:

- gpu-missing-drawing
- state-menus
- gpu-corrupt-drawing

**Comment by Sleepy93** [comment]
which is the correct? 

https://github.com/xenia-project/game-compatibility/issues/801
The ID and the name is the same...

**Comment by Razzile** [comment]
so it is

**Comment by Sakimotor** [comment]
Actually both are correct, one is from the Vulkan version and this one is from the OpenGL version.

**Comment by Razzile** [comment]
OpenGL backend will be removed soon so vulkan log is more useful
