### ISSUE TITLE
464F07F2 - Blackwater

### ISSUE THREAD

**Issue by eyesonlyuploads** [xenia-project/game-compatibility#807]
[Marketplace](https://marketplace.xbox.com/en-US/Product/Blackwater-Kinect/66acd000-77fe-1000-9115-d802464f07f2)

Tested on (https://github.com/benvanik/xenia/commit/22575af2127b021bfdd772f57c20907658316ed1)

# Issues:
Xenia Crashes

# Log:
[Log file](https://gist.github.com/eyesonlyuploads/bdbe907553d94494753891a580887a76)

# Screenshot(s):
![screenshot 19](https://user-images.githubusercontent.com/30570200/29238341-508824ba-7f2b-11e7-8ca7-69fbeee5f816.png)

# Labels:
state-crash

**Comment by Sleepy93** [comment]
# Log analysis:

# Unimplemented:
- XamPartyGetUserList
- XamPartySendGameInvites
- XamPartySetCustomData
- XamPartyGetBandwidth
- XamShowPartyUI
- XamShowCommunitySessionsUI

# Unknown GPU registers:
- 0081 
- 0082
- 0E00 
- 0E40
- 1E4E 

# Labels:
- state-crash
- kernel-unimplemented-features
