### ISSUE TITLE
4D5307ED - Banjo Kazooie: Nuts and Bolts

### ISSUE THREAD

**Issue by Sleepy93** [xenia-project/game-compatibility#814]
[Marketplace](http://marketplace.xbox.com/en-IE/Product/Banjo-Kazooie-N-n-B/66acd000-77fe-1000-9115-d8024d5307ed)

Tested on (https://github.com/benvanik/xenia/commit/1eac03a11cca9f19529931bd37f7cfd65afad2c2)

# Issues:
game starts plays intro and after it black screen.. 
as I hear that it's goes to menu but can't see anything.

# Unimplemented:
>  !> 00000048 NtQueryInformationFile(XFileXctdCompressionInformation) unimplemented

# GPU:
writes to unk. register
- 0081
- 0082
- 1E4E

# Log:
[banjokazooienuts.txt](https://github.com/xenia-project/game-compatibility/files/1253583/banjokazooienuts.txt)

# Labels:
- state-intro
- gpu-missing-drawing
- kernel-unimplemented-feature

**Comment by Razzile** [comment]
https://github.com/xenia-project/game-compatibility/issues/49
