### ISSUE TITLE
534507D6 - Sonic the Hedgehog 2006

### ISSUE THREAD

**Issue by LordOZ98** [xenia-project/game-compatibility#817]
[Marketplace] Removed from Marketplace for whatever reason

# Issues:
Crash after loading the file for the game.

# Log:
https://gist.github.com/LordOZ98/e8c1434fcfa6492ea7752dcda9a1cecd

# Screenshot(s):
https://s26.postimg.org/x139emcpl/Sans_titre.png

# Labels:
state-crash

**Comment by Sleepy93** [comment]
duplicated: Issue #285
