### ISSUE TITLE
584111F1 - Sonic CD

### ISSUE THREAD

**Issue by ccateni** [xenia-project/game-compatibility#823]
[Marketplace](http://marketplace.xbox.com/en-us/Product/Sonic-CD/66acd000-77fe-1000-9115-d802584111f1)

Tested on the Most Recent version of Xenia on my y700 gaming laptop. https://github.com/benvanik/xenia/commit/a7b6d91a2b2286e70592d6bcae9950dc65379070

# Issues:
(Crashes)

# Log:
[xenia.log](https://github.com/xenia-project/game-compatibility/files/1424736/xenia.log)

# Screenshot(s):
![soniccdxeniacrash](https://user-images.githubusercontent.com/25445255/32140040-4ac8bb76-bc29-11e7-9be7-24b18d419de4.png)

# Labels: state-crash

**Comment by gibbed** [comment]
https://github.com/xenia-project/game-compatibility/issues/151
