### ISSUE TITLE
NFS MW 2005 Black screen

### ISSUE THREAD

**Issue by Ramperson** [xenia-project/game-compatibility#840]
I have black screen after turning on, I can only hear the sounds.
After finish of the intro game crashes

The game I tried to run is Need For Speed Most Wanted 2005

Title ID is 454107D9

My PC:
GTX 1050 Ti (drivers 388.0.0)
Intel i5-7400@3.00GHz
8GB DDR4@2400MHz

**Comment by Sleepy93** [comment]
duplicated report.

https://github.com/xenia-project/game-compatibility/issues/491
