### ISSUE TITLE
584111D6 - Bejeweled 3

### ISSUE THREAD

**Issue by Blayer98** [xenia-project/game-compatibility#850]
[Marketplace](http://marketplace.xbox.com/en-GB/Product/Bejeweled-3/66acd000-77fe-1000-9115-d802584111d6)

Tested on https://github.com/benvanik/xenia/commit/ae8118d7872676dc0bf89660b7c4200a31a7aab9

# Issues:
There's no audio apart from the logo intro.

There are a couple of issues regarding controls, Hints don't appear in Classic Mode apart from the How to Play screen at the beginning, and when one should appear, the controls become bugged as selecting a gem and pressing WASD doesn't work, and the gem won't move. Disabling Hints and exiting and re-entering Classic Mode will fix the WASD issues.

When the bar becomes full in Classic Mode, you should automatically go to the next level, but this doesn't seem to happen on Xenia.

When completing or failing a quest in Quest Mode, the game will soft lock and the controls will become unresponsive.

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/1548722/xenia.zip)

# Undefined:
!> 00000028 undefined extern call to 82ACC4E4 XamShowMarketplaceUI

# Screenshot(s):
![image](https://user-images.githubusercontent.com/6663677/33842880-b8a67e12-de93-11e7-9961-123c4c29a71f.png)

# Labels:
state-gameplay
audio:silent

**Comment by Razzile** [comment]
https://github.com/xenia-project/game-compatibility/issues/453

**Comment by Blayer98** [comment]
Shall I also put what I said here onto that thread?

**Comment by Razzile** [comment]
@Blayer98 Yes please. I closed it because it was a duplicate not because your information was wrong :)
