### ISSUE TITLE
58410991 - ARKANOID Live!

### ISSUE THREAD

**Issue by Blayer98** [xenia-project/game-compatibility#851]
[Marketplace](https://marketplace.xbox.com/en-GB/Product/ARKANOID-Live/66acd000-77fe-1000-9115-d80258410991)

Tested on https://github.com/benvanik/xenia/commit/ae8118d7872676dc0bf89660b7c4200a31a7aab9

# Issues:
Game seems to have issues with graphics in the menu as well as sound effects being slightly delayed. Other than that, the game works fine.

# Undefined:
!> 0000002C undefined extern call to 821088D0 XamShowAchievementsUI
!> 0000002C undefined extern call to 821088F0 XamShowMarketplaceUI

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/1548782/xenia.zip)

# Screenshot(s):
![image](https://user-images.githubusercontent.com/6663677/33844674-e4dcf6aa-de98-11e7-8e87-b8427e14b38f.png)
![image](https://user-images.githubusercontent.com/6663677/33844679-eb523bb2-de98-11e7-899c-5c6f17378e1f.png)

# Labels:
state:playable

**Comment by Razzile** [comment]
https://github.com/xenia-project/game-compatibility/issues/375
