### ISSUE TITLE
5345881E - Sonic Unleashed Demo

### ISSUE THREAD

**Issue by ccateni** [xenia-project/game-compatibility#854]
[Marketplace](http://marketplace.xbox.com/en-US/Product/Sonic-Unleashed-Demo/00000000-0000-400d-80df-00015345881e)

Tested on (https://github.com/benvanik/xenia/commit/5da59a95c95be0fa6e5578642c6c0ec85fd362b5)

# Issues:
(state of the game)

# Log:
[xenialog.zip](https://github.com/xenia-project/game-compatibility/files/1565295/xenialog.zip)

# Screenshot(s):
![sucrash](https://user-images.githubusercontent.com/25445255/34076312-4ed324ba-e2b0-11e7-9957-80e654a4edda.png)

# Labels:

**Comment by ccateni** [comment]
https://github.com/xenia-project/game-compatibility/labels/state-crash

**Comment by ccateni** [comment]
that was an error on my part (the closing of the post).

**Comment by Razzile** [comment]
https://github.com/xenia-project/game-compatibility/issues/790
