### ISSUE TITLE
4D530910 - Forza Motorsport 4 

### ISSUE THREAD

**Issue by marsselluo** [xenia-project/game-compatibility#855]
The game shows part of the menus (about 40 % of the screen, see the picture) and crash before enter the game with the message "There's been an issue reading content from the game disc.
This is likely caused by bad or unimplemented file IO calls."
Sorry for my bad english.
![sem titul0o](https://user-images.githubusercontent.com/30375393/34320263-09e14d82-e7dd-11e7-997e-3cd9c473a5f9.jpg)
![sem titulo](https://user-images.githubusercontent.com/30375393/34320264-0a045b88-e7dd-11e7-9a8e-7b1e808319cf.jpg)

[xenia.zip](https://github.com/xenia-project/game-compatibility/files/1584170/xenia.zip)

**Comment by Sleepy93** [comment]
This issue is already created.

#442

**Comment by marsselluo** [comment]
Sorry, I didn't see.
