### ISSUE TITLE
555307E5 Naruto Rise Of Ninja Black Screen

### ISSUE THREAD

**Issue by jejedu82370** [xenia-project/game-compatibility#856]
Hello I'm French that's why there will probably be fault
I have a black screen as I launch the game
I made a video to show what I'm doing here is the link:
https://www.youtube.com/watch?v=proSUlXeCv8
Thank you for helping me it's been 1 month see 2 that I try but nothing to do I'm on windows 10

**Comment by Sleepy93** [comment]
Hello,

This issue is already reported.

#131

**Comment by Razzile** [comment]
https://github.com/xenia-project/game-compatibility/issues/131
