### ISSUE TITLE
Sonic unleashed demo crash

### ISSUE THREAD

**Issue by DavidPires** [xenia-project/game-compatibility#863]
[Marketplace](http://marketplace.xbox.com/...)

Tested on (xenia commit link)

# Issues:
(state of the game)

# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here (replacing this text).

# Screenshot(s):
![](Screenshot URL)

# Labels:
(recommended labels)

**Comment by Sleepy93** [comment]
This issue is already reported.
[#790](https://github.com/xenia-project/game-compatibility/issues/790)

**Comment by DavidPires** [comment]
then what is the solution? i don't see it

**Comment by raynebc** [comment]
The solution is to wait for resolution of the pre-existing report (https://github.com/xenia-project/game-compatibility/issues/790).

**Comment by DavidPires** [comment]
then the compatiblity list is wrong and should be fixed right away
