### ISSUE TITLE
425307F5 - Wolfenstein: The New Order

### ISSUE THREAD

**Issue by zemzema** [xenia-project/game-compatibility#873]
[Marketplace](http://marketplace.xbox.com/en-US/Product/Wolfenstein-The-New-Order/66acd000-77fe-1000-9115-d802425307f5)

Tested on (https://github.com/benvanik/xenia/commit/24baf58ae39b67f9c189db7542ea7a7f6d513d11)

# Issues:
(Not working... Message on beginning "The guest has crashed"
Game comes on 4 DVD.)

# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/1752971/xenia.zip)

# Screenshot(s):

# Labels:
(state-nothing)

**Comment by somereallygoodname** [comment]
# Correction:

[Marketplace](http://marketplace.xbox.com/en-US/Product/Wolfenstein-The-New-Order/66acd000-77fe-1000-9115-d802425307f5)

**Comment by zemzema** [comment]
# Tested on:
https://github.com/benvanik/xenia/commit/3e216f0553263cfe9de2df51ef11ac3930d73f81

# Logs:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/2042681/xenia.zip)

# Labels:
(state-crash-guest)

**Comment by Drive251** [comment]
duplicated with https://github.com/xenia-project/game-compatibility/issues/459
