### ISSUE TITLE
454108CF - Dante's Inferno

### ISSUE THREAD

**Issue by TecladistaProd** [xenia-project/game-compatibility#882]
notebook dell inspiron, intel i5 2,7ghz 4core, 8gb ram, gpu0 intel 4gb, gpu1 geforce 920m 4g
![image](https://user-images.githubusercontent.com/26743405/36632072-5f5d9748-1960-11e8-809a-959b65cf8327.png)
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/1754566/xenia.zip)

**Comment by TecladistaProd** [comment]
xenia.zip is the log file

**Comment by agrecalypse** [comment]
Please append to Issue #164 that already exists for this game.

**Comment by TecladistaProd** [comment]
@agrecalypse , how i make this please? i don't how to work with github very well
