### ISSUE TITLE
534307E7 - Just Cause 2

### ISSUE THREAD

**Issue by zemzema** [xenia-project/game-compatibility#898]
[Marketplace](http://marketplace.xbox.com/en-us/Product/Just-Cause-2/66acd000-77fe-1000-9115-d802534307e7)

Tested on (https://github.com/benvanik/xenia/commit/6b8a34c9ba7e4886d7c42de1658682acfffd0a11 )

# Issues:
Game crash!

# Log:
[just_cause_2.zip](https://github.com/xenia-project/game-compatibility/files/1794066/just_cause_2.zip)

# Screenshot(s):
![screenshot 50](https://user-images.githubusercontent.com/33085810/37165226-65b07a02-22fc-11e8-8bb1-d1d9cba9763e.png)

# Labels:
(state-crash)

**Comment by Razzile** [comment]
https://github.com/xenia-project/game-compatibility/issues/466
