### ISSUE TITLE
Tekken Tag Tournament 2 - Crashes before menu screen

### ISSUE THREAD

**Issue by Rokezo** [xenia-project/game-compatibility#900]
Tested on (https://appveyorcidata.blob.core.windows.net/benvanik-17297/xenia/1-0-1215-master/3va4hnl5o79db4s2/xenia-master.zip)

# Issues:
It crashes when I get to the name logo

# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here ([xenia.log](https://github.com/xenia-project/game-compatibility/files/1818767/xenia.log)).

# Screenshot(s):
![](https://snag.gy/SCX0BT.jpg)

If anyone could tell me the possible flaws my system has or something I did wrong, please tell me. Thanks!

**Comment by Sleepy93** [comment]
# Log Analysis

# Issues
> !> 000000D4 NtQueryInformationFile(XFileXctdCompressionInformation) unimplemented
> !> 00000028 ResolvePath(\Device\) failed - no root found
> !> 00000028 ResolvePath(\Device\Harddisk0\) failed - no root found

# GPU 
> !> 00000028 GPU: Read from unknown register (044B)
> w> 00000004 GPU: Write to unknown register (0081 = 80010000)
> w> 00000004 GPU: Write to unknown register (0082 = 00000000)
> w> 00000004 GPU: Write to unknown register (1E4E = 00000000)

Labels:
- state-intro
- kernel-unimplemented-feature

**Comment by Razzile** [comment]
https://github.com/xenia-project/game-compatibility/issues/295

**Comment by Rokezo** [comment]
alright so what does all these mean for me to do? duplicated as in? if it's too much to ask, could you perhaps explain whatever you stated above?

**Comment by Razzile** [comment]
@Rokezo the issues here are used to power the game compatibility page on the xenia website, therefore there can't be any duplicate issues of the same game or issues that aren't in the correct issue format.

I would submit your findings to the issue that already exists for this game instead
