### ISSUE TITLE
534507D6 - Sonic The Hedgehog

### ISSUE THREAD

**Issue by eunhon93** [xenia-project/game-compatibility#904]
# Issues:
Textures not loading

# Log:

[xenia.zip](https://github.com/xenia-project/game-compatibility/files/1844215/xenia.zip)

# Screenshot(s):
![issue](https://user-images.githubusercontent.com/6225779/37862456-7b164600-2f23-11e8-98b9-ed42c13fa003.PNG)

**Comment by Razzile** [comment]
https://github.com/xenia-project/game-compatibility/issues/285
