### ISSUE TITLE
555307D5 - Ghost Recon Advanced Warfighter

### ISSUE THREAD

**Issue by dudefrom531** [xenia-project/game-compatibility#907]
[Marketplace](https://marketplace.xbox.com/en-us/Product/TCs-GRAW/66acd000-77fe-1000-9115-d802555307d5)

Tested on https://github.com/benvanik/xenia/commit/6b8a34c9ba7e4886d7c42de1658682acfffd0a11

# Issues:
Crashes the emulator a few seconds after the executable is selected.

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/1866109/xenia.zip)

# Screenshot(s):
![](Screenshot URL)

# Labels:
(state-crash)

**Comment by Razzile** [comment]
just noticed https://github.com/xenia-project/game-compatibility/issues/451
please report issues for this game in that thread
