### ISSUE TITLE
4E4D083A - Dark Souls

### ISSUE THREAD

**Issue by krikic** [xenia-project/game-compatibility#936]
[Marketplace](https://marketplace.xbox.com/en-US/Product/DARK-SOULS-II-Add-on-Bundle/d1118d42-9cb5-4a49-a8a6-4ea4e886c5b8.)

Tested on (xenia commit link)

# Issues:
(state of the game)

# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here (replacing this text).

# Screenshot(s):
![](Screenshot URL)

# Labels:
(recommended labels)

**Comment by Razzile** [comment]
will reopen when you've added content to the issue.
might be a goo idea to write the issue before you post it
