### ISSUE TITLE
454107DC - Burnout Revenge PAL

### ISSUE THREAD

**Issue by voltagex** [xenia-project/game-compatibility#95]
[Marketplace](http://marketplace.xbox.com/en-AU/Product/Burnout-Revenge/66acd000-77fe-1000-9115-d802454107dc)

xenia-project/xenia@fc7695f

![untitled](https://cloud.githubusercontent.com/assets/159567/8477351/c7c1f580-210c-11e5-82b7-ccbf1bd5e960.jpg)

Crash at loading screen

```
>   xenia.exe!xe::cpu::backend::x64::PACK::Emit8_IN_16(xe::cpu::backend::x64::X64Emitter & e, const xe::cpu::backend::x64::`anonymous-namespace'::I<101,xe::cpu::backend::x64::`anonymous namespace'::V128<-1>,xe::cpu::backend::x64::A0x3328766d::V128<-1>,xe::cpu::backend::x64::A0x3328766d::V128<-1> > & i, unsigned int flags) Line 6186   C++
```

[213B2D4C.zip](https://github.com/xenia-project/game-compatibility/files/1099481/213B2D4C.zip)

**Comment by DPersonalized** [comment]
Burnout Revenge now goes in-game, according to this video:
https://www.youtube.com/watch?v=Z2Vk2cTIpiQ

That's for the PAL version, at least.

**Comment by Razzile** [comment]
sate-gameplay i'm guessing

**Comment by voltagex** [comment]
Doesn't seem to like my ISO that worked on previous versions: 
```
!> 00004B34 Failed to verify disc image header: -30
X> 00004B34 Unable to mount disc image; file not found or corrupt.
```

Mounting the image and running the executable directly allows me to get all the way to level selection, then a crash.

```
Unhandled exception at 0x0000000068758538 (nvoglv64.dll) in xenia.exe: Fatal program exit requested.
```

I'm going to try to source a better copy of the game.

[xenia.zip](https://github.com/xenia-project/game-compatibility/files/1099482/xenia.zip)

**Comment by Razzile** [comment]
that error looks like the graphics driver crashed

**Comment by Parovozik** [comment]
Title ID: 454107DC - Burnout Revenge
Tested on (https://github.com/benvanik/xenia/commit/2a52156edf4ecc02d9083c31d495e0a927d26438) + (https://github.com/benvanik/xenia/issues/779)
# Log (clear Master build):
[Burnout Revenge.txt](https://github.com/xenia-project/game-compatibility/files/1772911/Burnout.Revenge.txt)
# Issues:
Memory Leak and black screen space on 3D. Status - ingame
# Screenshots:
![bandicam 2018-03-02 00-03-07-548](https://user-images.githubusercontent.com/19775644/36871727-35a29914-1db4-11e8-8a85-aecced38d26f.jpg)
![bandicam 2018-03-02 00-03-45-827](https://user-images.githubusercontent.com/19775644/36871732-3817667a-1db4-11e8-8187-b5fe42215751.jpg)

**Comment by Eurose209** [comment]
![image](https://user-images.githubusercontent.com/8225831/46587181-26c6fd80-ca80-11e8-82d6-fe8983c6bca8.png)
Objects now render correctly, but HUD is cut-off at bottom.

**Comment by Memorix101** [comment]
Hey, I get the same results as Eurose209 with the Demo. Also, music is not playing and as you see 
post-proccessing somehow yellowish.
![screenshot 83](https://user-images.githubusercontent.com/1466920/48369915-24c41000-e6b8-11e8-8230-9655576ffb93.png)
![screenshot 85](https://user-images.githubusercontent.com/1466920/48369940-35748600-e6b8-11e8-87df-c632a0c5b163.png)

**Comment by Memorix101** [comment]
The latest version fixed the HUD issue but framerate is not stable anymore (sometimes drops).
![screenshot 93](https://user-images.githubusercontent.com/1466920/49333303-bee2ee00-f5bc-11e8-86df-20c1bda73e00.png)

**Comment by Prism019** [comment]
The title has the wrong TitleID.
The correct TitleID is 454107DC.

**Comment by Margen67** [comment]
Superseded by #914.
